package de.speedbanking.checkdigit.de;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatIllegalArgumentException;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.EnumSource;

/**
 * Unit tests for {@link GermanCheckDigitMethod}.
 * <p>
 * Expected check digits for {@code calculate_knownVectors} were generated by an
 * independent Python re-implementation of the documented weight tables and formulas
 * (mirroring the javadoc on each constant, not the Java source), then verified to
 * round-trip through the actual production code. They exercise the arithmetic in this
 * class but are <strong>not</strong> a substitute for verification against real-world
 * BLZ/Kontonummer pairs from the Bundesbank reference source. "Invalid" vectors are
 * produced by incrementing (mod 10) the digit at the position the method under test
 * actually compares — for chained/fallback methods this is occasionally not enough to
 * guarantee overall invalidity if a later fallback branch happens to accept the mutated
 * number too; each such vector was confirmed by running this suite, not just derived
 * algebraically.
 */
@SuppressWarnings("checkstyle:MethodName")
final class GermanCheckDigitMethodTest {

    // BLZ content is irrelevant to almost all implemented methods - use a fixed placeholder.
    private static final char[] BLZ = "10000000".toCharArray();

    // Methods 00-09 (original batch)

    @ParameterizedTest(name = "[{index}] method {0}: account {1}")
    @CsvSource({
        "00, 1234567897, true",
        "00, 1234567890, false", // wrong check digit
        "01, 1234567899, true",
        "01, 1234567890, false",
        "02, 1234567897, true",
        "02, 1234567890, false",
        "03, 1234567890, true",
        "03, 1234567891, false",
        "04, 1234567892, true",
        "04, 1234567890, false",
        "05, 1234567897, true",
        "05, 1234567890, false",
        "07, 1111111111, true",
        "07, 1111111110, false",
    })
    void calculate_knownVectors_00to09(String code, String account, boolean expectedValid) {
        assertVector(code, account, expectedValid);
    }

    @Test
    void calculate_m04_remainderTen_neverMatches() {
        // sum(weights 4,3,2,7,6,5,4,3,2 over "300000000") = 3*4 = 12; 12 % 11 = 1
        // M04: (11 - 1) % 11 = 10 -> can never equal a single decimal digit
        CheckDigitResult result = GermanCheckDigitMethod.M04.calculate(BLZ, "3000000000".toCharArray());

        assertThat(result.isChecked()).isTrue();
        assertThat(result.isValid()).isFalse();
    }

    @Test
    void calculate_m06_remainderTen_collapsesToZero() {
        // Same input as calculate_m04_remainderTen_neverMatches, but M06 clamps
        // any raw value > 9 (i.e. both 10 and 11) to 0, unlike M04 which only clamps 11.
        CheckDigitResult result = GermanCheckDigitMethod.M06.calculate(BLZ, "3000000000".toCharArray());

        assertThat(result.isChecked()).isTrue();
        assertThat(result.isValid()).isTrue();
    }

    @Test
    void calculate_m08_belowThreshold_notChecked() {
        CheckDigitResult result = GermanCheckDigitMethod.M08.calculate(BLZ, "0000012345".toCharArray());

        assertThat(result.isChecked()).isFalse();
        assertThat(result.isValid()).isTrue();
    }

    @Test
    void calculate_m08_atOrAboveThreshold_usesM00Formula() {
        CheckDigitResult valid = GermanCheckDigitMethod.M08.calculate(BLZ, "1234567897".toCharArray());
        CheckDigitResult invalid = GermanCheckDigitMethod.M08.calculate(BLZ, "1234567890".toCharArray());

        assertThat(valid.isChecked()).isTrue();
        assertThat(valid.isValid()).isTrue();

        assertThat(invalid.isChecked()).isTrue();
        assertThat(invalid.isValid()).isFalse();
    }

    @Test
    void calculate_m09_alwaysNotChecked() {
        CheckDigitResult result = GermanCheckDigitMethod.M09.calculate(BLZ, "0000000000".toCharArray());

        assertThat(result.isChecked()).isFalse();
        assertThat(result.isValid()).isTrue();
    }

    // Methods 10-D9 (extended batch): generic weighted-formula vectors

    @ParameterizedTest(name = "[{index}] method {0}: account {1}")
    @CsvSource({
        "10, 1234567890, true",
        "10, 1234567891, false",
        "11, 1234567899, true",
        "11, 1234567890, false",
        "13, 0123456600, true",
        "13, 0123456700, false",
        "14, 0001234560, true",
        "14, 0001234561, false",
        "15, 0000012343, true",
        "15, 0000012344, false",
        "16, 1234567892, true",
        "16, 1234567893, false",
        "17, 0123456900, true",
        "17, 0123456000, false",
        "18, 1234567899, true",
        "18, 1234567890, false",
        "19, 1234567898, true",
        "19, 1234567899, false",
        "20, 1234567896, true",
        "20, 1234567897, false",
        "21, 1234567893, true",
        "21, 1234567894, false",
        "22, 1234567895, true",
        "22, 1234567896, false",
        "23, 1234560000, true",
        "23, 1234561000, false",
        "24, 1234567898, true",
        "24, 1234567899, false",
        "25, 1834567890, true",
        "25, 1834567891, false",
        "26, 1234567400, true",
        "26, 1234567500, false",
        "27, 1234567895, true",
        "27, 1234567896, false",
        "28, 1234567900, true",
        "28, 1234567000, false",
        "29, 1234567895, true",
        "29, 1234567896, false",
        "30, 1234567892, true",
        "30, 1234567893, false",
        "31, 1111111111, true",
        "31, 1111111112, false",
        "32, 0001234560, true",
        "32, 0001234561, false",
        "33, 0000123455, true",
        "33, 0000123456, false",
        "34, 1234567100, true",
        "34, 1234567200, false",
        "36, 0000012343, true",
        "36, 0000012344, false",
        "38, 0001234562, true",
        "38, 0001234563, false",
        "40, 1234567899, true",
        "40, 1234567890, false",
        "41, 1230567891, true",
        "41, 1230567892, false",
        "42, 0123456789, true",
        "42, 0123456780, false",
        "43, 1234567895, true",
        "43, 1234567896, false",
        "44, 1234567891, true",
        "44, 1234567892, false",
        "46, 0012345500, true",
        "46, 0012345600, false",
        "48, 0012345600, true",
        "48, 0012345610, false",
        "55, 1234567895, true",
        "55, 1234567896, false",
        "56, 1234567892, true",
        "56, 1234567893, false",
        "58, 1234567892, true",
        "58, 1234567893, false",
        "60, 0012345674, true",
        "60, 0012345675, false",
        "61, 1234567490, true",
        "61, 1234567590, false",
        "63, 0123456600, true",
        "63, 0123456700, false",
        "64, 1234562000, true",
        "64, 1234563000, false",
        "65, 1234567480, true",
        "65, 1234567580, false",
        "66, 0123456784, true",
        "66, 0123456785, false",
        "67, 1234567400, true",
        "67, 1234567500, false",
        "68, 0123456782, true",
        "68, 0123456783, false",
        "69, 1234567900, true",
        "69, 1234567000, false",
        "70, 1234567892, true",
        "70, 1234567893, false",
        "71, 0123456001, true",
        "71, 0123456002, false",
        "73, 0001234566, true",
        "73, 0001234568, false",
        "74, 1234567897, true",
        "74, 1234567898, false",
        "76, 0112345200, true",
        "76, 0112345300, false",
        "78, 1234567897, true",
        "78, 1234567898, false",
        "85, 0001234560, true",
        "85, 0001234561, false",
        "88, 0001234560, true",
        "88, 0001234561, false",
        "90, 0001234560, true",
        "90, 0001234561, false",
        "91, 1234560000, true",
        "91, 1234561000, false",
        "92, 0001234569, true",
        "92, 0001234560, false",
        "93, 6714790000, true", // Fall a, Modulus 11 (Bundesbank test vector)
        "93, 6714780000, false",
        "94, 1234567893, true",
        "94, 1234567894, false",
        "95, 1234567892, true",
        "95, 1234567893, false",
        "98, 0012345676, true",
        "98, 0012345677, false",
        "99, 1234567892, true",
        "99, 1234567893, false",
        "A0, 1000000123, true",
        "A0, 1000000124, false",
        "A1, 1234567891, true",
        "A1, 1234567892, false",
        "A4, 0004711173, true", // Variante 1 (Bundesbank test vector)
        "A4, 0000399443, false", // fails Variante 1, 2 and 4 (Bundesbank test vector)
        "B0, 1000000406, true", // Variante 2 / M06 (Bundesbank test vector)
        "B0, 1000000405, false",
        "B4, 9941510001, true", // Variante 1 / M00 (Bundesbank test vector)
        "B4, 9941510002, false",
        "B9, 0012345673, true",
        "B9, 0012345674, false",
        "C5, 0000123455, true",
        "C5, 0000123456, false",
        "C6, 7000005024, true", // Bundesbank worked example
        "C6, 7000005025, false",
        "D0, 1234567896, true",
        "D0, 1234567897, false",
        "D1, 1234567896, true",
        "D1, 1234567897, false",
    })
    void calculate_knownVectors_extended(String code, String account, boolean expectedValid) {
        assertVector(code, account, expectedValid);
    }

    // Branch-coverage vectors for methods with several internal dispatch/fallback branches that the vectors above don't reach (each comment names the branch hit)

    @ParameterizedTest(name = "[{index}] method {0}: account {1}")
    @CsvSource(delimiter = '|', value = {
        "C5 | 0000900000 | false", // digits 1-4 all 0, digit 5 out of [1,8] range
        "C5 | 0500009000 | true",  // digit 1 == 0, digit 2 (1-8) in range, formula compared at index 6
        "C5 | 0500000000 | false", // same branch, formula mismatch
        "C5 | 1234567890 | false", // leading digit 1 -> delegates to M29 (invalid)
        "C5 | 9234567890 | true",  // leading digit 9 -> delegates to M29 (valid)
        "C5 | 3234567890 | false", // leading digit 3 -> delegates to M00 (invalid)
        "C5 | 2000000000 | false", // none of the special cases apply -> unconditional false
        "51 | 7914220587 | true",  // digit 3 != 9, sumA (Modulus 11, weights 7-2) valid
        "51 | 2684737828 | true",  // sumA invalid, sumB (Modulus 11, weights 6-2) valid
        "51 | 5168795486 | true",  // sumA/sumB invalid, sumC (Modulus 10) valid
        "51 | 2914177763 | true",  // sumA/sumB/sumC invalid, digit 10 < 7, Modulus-7 fallback valid
        "51 | 6634876475 | false", // same fallback, formula mismatch
        "51 | 0105244939 | false", // sumA/sumB/sumC invalid, digit 10 >= 7 -> rejected outright
        "B8 | 2735730177 | true",  // primary Modulus-11 formula valid
        "B8 | 1706859643 | true",  // primary formula invalid, M29 fallback valid
        "B8 | 4273675928 | false", // both invalid, outside the 'not checked' exception ranges
        "84 | 2806520667 | true",  // no Ausnahme, sumA (Modulus 11) valid
        "84 | 3607756696 | true",  // no Ausnahme, sumA invalid, sumB (Modulus 7) valid
        "84 | 9400189902 | true",  // no Ausnahme, sumA/sumB invalid, sumC (Modulus 10) valid
        "84 | 2100969422 | false", // no Ausnahme, all three formulas invalid
        "84 | 0898857649 | true",  // Ausnahme applies, first Modulus-11 variant matches
        "84 | 5791244665 | true",  // Ausnahme applies, first variant fails, second matches
        "96 | 1715391401 | true",  // valid via M19
        "96 | 1313337832 | true",  // M19 invalid, valid via M00
        "96 | 0041465264 | true",  // M19/M00 invalid, digit 1 == 0, value inside reserved range
        "96 | 0642729359 | false", // M19/M00 invalid, digit 1 == 0, value outside reserved range
        "96 | 1041465264 | false", // M19/M00 invalid, digit 1 != 0 -> always false
        "A8 | 2003798909 | true",  // digit 3 != 9, sumA (Modulus 11, weights 7-2) valid
        "A8 | 4809387549 | true",  // sumA invalid, sumB (Modulus 10) valid
        "A8 | 8001465264 | false", // sumA/sumB invalid
        "35 | 6187376609 | true",  // remainder in [1,9], normal comparison
        "35 | 8041465264 | false", // same branch, mismatch
        "35 | 2879069222 | true",  // remainder == 10 -> compares digit 9 to digit 10 instead
        "35 | 2091253128 | false", // same branch, digits differ
        "35 | 1739348370 | true",  // sum % 11 == 0 -> remainder 11 collapses to 0
        "86 | 4809387549 | true",  // own formula (Modulus 10) valid
        "86 | 4703625701 | true",  // own formula invalid, delegates to M33 (valid)
        "86 | 8001465264 | false", // own formula and M33 delegate both invalid
        "95 | 0041465264 | false", // digit 1 == 0 but outside every reserved range -> formula applies
        "57 | 5100000003 | true",  // 'first' selects the WEIGHTS_M57A formula, compared at index 9
        "57 | 5100000004 | false", // same branch, mismatch
        "57 | 3230000000 | true",  // 'first' selects the WEIGHTS_M57B formula, compared at index 2
        "57 | 3240000000 | false", // same branch, mismatch
    })
    void calculate_knownVectors_branchCoverage(String code, String account, boolean expectedValid) {
        assertVector(code, account, expectedValid);
    }

    @Test
    void calculate_c5_leadingZerosThenDigit3InRange_delegatesToM09() {
        assertThat(GermanCheckDigitMethod.C5.calculate(BLZ, "0030000000".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_c5_leadingSevenOrEightException_delegatesToM09() {
        assertThat(GermanCheckDigitMethod.C5.calculate(BLZ, "7000000000".toCharArray()).isChecked()).isFalse();
        assertThat(GermanCheckDigitMethod.C5.calculate(BLZ, "8500000000".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_b8_leading2Or3DigitsInExceptionRange_notChecked() {
        assertThat(GermanCheckDigitMethod.B8.calculate(BLZ, "5614443803".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_m95_reservedRanges_allFiveVariants_notChecked() {
        assertThat(GermanCheckDigitMethod.M95.calculate(BLZ, "0013798909".toCharArray()).isChecked()).isFalse();
        assertThat(GermanCheckDigitMethod.M95.calculate(BLZ, "0409770020".toCharArray()).isChecked()).isFalse();
        assertThat(GermanCheckDigitMethod.M95.calculate(BLZ, "0715391401".toCharArray()).isChecked()).isFalse();
        assertThat(GermanCheckDigitMethod.M95.calculate(BLZ, "0969854394".toCharArray()).isChecked()).isFalse();
    }

    private static void assertVector(String code, String account, boolean expectedValid) {
        GermanCheckDigitMethod method = GermanCheckDigitMethod.fromCode(code);

        CheckDigitResult result = method.calculate(BLZ, account.toCharArray());

        assertThat(result.isChecked()).as("method %s should perform a real check for %s", code, account).isTrue();
        assertThat(result.isValid()).as("method %s, account %s", code, account).isEqualTo(expectedValid);
    }

    // Methods with a "not checked" outcome for specific inputs

    @Test
    void calculate_m45_leadingZeroOrDigit5IsOne_notChecked() {
        assertThat(GermanCheckDigitMethod.M45.calculate(BLZ, "0000000000".toCharArray()).isChecked()).isFalse();
        assertThat(GermanCheckDigitMethod.M45.calculate(BLZ, "0000100000".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_m45_otherwise_delegatesToM00() {
        CheckDigitResult result = GermanCheckDigitMethod.M45.calculate(BLZ, "9234567890".toCharArray());
        assertThat(result.isChecked()).isTrue();
        assertThat(result.isValid()).isTrue();
    }

    @Test
    void calculate_m59_leadingTwoZeros_notChecked() {
        assertThat(GermanCheckDigitMethod.M59.calculate(BLZ, "0012345678".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_m59_otherwise_delegatesToM00() {
        CheckDigitResult result = GermanCheckDigitMethod.M59.calculate(BLZ, "1234567897".toCharArray());
        assertThat(result.isValid()).isTrue();
    }

    @Test
    void calculate_m68_digit1Is4_notChecked() {
        assertThat(GermanCheckDigitMethod.M68.calculate(BLZ, "0400000000".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_m69_digit1Is3_notChecked() {
        assertThat(GermanCheckDigitMethod.M69.calculate(BLZ, "9300000000".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_m78_exceptionRange_notChecked() {
        assertThat(GermanCheckDigitMethod.M78.calculate(BLZ, "0012345678".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_m95_reservedRange_notChecked() {
        // account value 500000 falls into the documented [1, 1999999] reserved range
        assertThat(GermanCheckDigitMethod.M95.calculate(BLZ, "0000500000".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_m99_exceptionRange_notChecked() {
        assertThat(GermanCheckDigitMethod.M99.calculate(BLZ, "0400000000".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_a0_leadingSevenZeros_notChecked() {
        assertThat(GermanCheckDigitMethod.A0.calculate(BLZ, "0000000123".toCharArray()).isChecked()).isFalse();
    }

    @Test
    void calculate_b7_outsideRange_notChecked() {
        assertThat(GermanCheckDigitMethod.B7.calculate(BLZ, "0000000001".toCharArray()).isChecked()).isFalse();
    }

    // Delegating / chained methods

    @Test
    void calculate_m49_delegatesToM00ThenM01() {
        // "1234567897" validates under M00
        assertThat(GermanCheckDigitMethod.M49.calculate(BLZ, "1234567897".toCharArray()).isValid()).isTrue();
        // "1234567899" validates under M01 but not M00
        assertThat(GermanCheckDigitMethod.M01.calculate(BLZ, "1234567899".toCharArray()).isValid()).isTrue();
        assertThat(GermanCheckDigitMethod.M00.calculate(BLZ, "1234567899".toCharArray()).isValid()).isFalse();
        assertThat(GermanCheckDigitMethod.M49.calculate(BLZ, "1234567899".toCharArray()).isValid()).isTrue();
    }

    @Test
    void calculate_m81_sachkonto_delegatesToM51() {
        // digit 3 (index 2) == 9 selects the M51 Sachkonten branch
        CheckDigitResult direct = GermanCheckDigitMethod.M51.calculate(BLZ, "1290000123".toCharArray());
        CheckDigitResult delegated = GermanCheckDigitMethod.M81.calculate(BLZ, "1290000123".toCharArray());
        assertThat(delegated).isEqualTo(direct);
    }

    @Test
    void calculate_m81_nonSachkonto_delegatesToM32() {
        CheckDigitResult direct = GermanCheckDigitMethod.M32.calculate(BLZ, "0001234560".toCharArray());
        CheckDigitResult delegated = GermanCheckDigitMethod.M81.calculate(BLZ, "0001234560".toCharArray());
        assertThat(delegated).isEqualTo(direct);
    }

    @Test
    void calculate_a6_digit2Is8_delegatesToM00() {
        CheckDigitResult result = GermanCheckDigitMethod.A6.calculate(BLZ, "1834567890".toCharArray());
        assertThat(result).isEqualTo(GermanCheckDigitMethod.M00.calculate(BLZ, "1834567890".toCharArray()));
    }

    @Test
    void calculate_a6_otherwise_delegatesToM01() {
        CheckDigitResult result = GermanCheckDigitMethod.A6.calculate(BLZ, "1034567890".toCharArray());
        assertThat(result).isEqualTo(GermanCheckDigitMethod.M01.calculate(BLZ, "1034567890".toCharArray()));
    }

    @Test
    void calculate_c7_documentedReservation_fallsBackToM06Unmodified() {
        // C7's javadoc documents this as "implemented with reservation": the spec calls
        // for a modified M06, but the reference source's own tests pass with the plain
        // M06 formula - replicated as-is here.
        CheckDigitResult m06Direct = GermanCheckDigitMethod.M06.calculate(BLZ, "1234567892".toCharArray());
        CheckDigitResult c7Result = GermanCheckDigitMethod.C7.calculate(BLZ, "1234567892".toCharArray());
        assertThat(c7Result).isEqualTo(m06Direct);
    }

    // Structurally distinct methods (loops, range dispatch, shift-retry)

    @Test
    void calculate_m50_firstAttemptSucceeds() {
        CheckDigitResult result = GermanCheckDigitMethod.M50.calculate(BLZ, "1234560000".toCharArray());
        assertThat(result.isValid()).isTrue();
    }

    @Test
    void calculate_m50_fallsBackToShiftedAttempt() {
        // First attempt (digits 1-6, weights 7,6,5,4,3,2 vs. index 6) deliberately fails;
        // shifting digits 4-10 left by three and retrying the same formula on the
        // shifted number (padded with three trailing zeros) must then succeed.
        char[] account = "0001234560".toCharArray();
        assertThat(GermanCheckDigitMethod.M50.calculate(BLZ, "9991234561".toCharArray()).isValid()).isFalse();

        CheckDigitResult result = GermanCheckDigitMethod.M50.calculate(BLZ, account);
        // shifted number is "1234560" + "000" = "1234560000", which is the M91-variant-1-style
        // vector known to be valid for weights 7,6,5,4,3,2 over index 0-5 compared at index 6
        assertThat(result.isValid()).isTrue();
    }

    @Test
    void calculate_m91_triesAllFourVariantsBeforeRejecting() {
        assertThat(GermanCheckDigitMethod.M91.calculate(BLZ, "0000000000".toCharArray()).isValid()).isTrue();
        assertThat(GermanCheckDigitMethod.M91.calculate(BLZ, "1234567891".toCharArray()).isValid()).isFalse();
    }

    @Test
    void calculate_m57_leadingZeros_alwaysInvalid() {
        assertThat(GermanCheckDigitMethod.M57.calculate(BLZ, "0000000000".toCharArray()).isValid()).isFalse();
    }

    @Test
    void calculate_m57_repeatedSevenOrEightPrefix_alwaysValid() {
        assertThat(GermanCheckDigitMethod.M57.calculate(BLZ, "7777770000".toCharArray()).isValid()).isTrue();
        assertThat(GermanCheckDigitMethod.M57.calculate(BLZ, "8888880000".toCharArray()).isValid()).isTrue();
    }

    @Test
    void calculate_m57_documentedAlwaysValidPrefixes() {
        assertThat(GermanCheckDigitMethod.M57.calculate(BLZ, "4000000000".toCharArray()).isValid()).isTrue();
        assertThat(GermanCheckDigitMethod.M57.calculate(BLZ, "9900000000".toCharArray()).isValid()).isTrue();
    }

    @Test
    void calculate_m57_rangeOneToThirtyOne_dependsOnEmbeddedMonth() {
        // "first" = 05, digits 3-4 = 01 (valid month), digit 7 = 0 (< 5)
        assertThat(GermanCheckDigitMethod.M57.calculate(BLZ, "0501000000".toCharArray()).isValid()).isTrue();
        // digits 3-4 = 13 is not a valid month
        assertThat(GermanCheckDigitMethod.M57.calculate(BLZ, "0513000000".toCharArray()).isValid()).isFalse();
    }

    @Test
    void calculate_m57_rangeOneToThirtyOne_invalidMonth_rejected() {
        // "first" = 15, digits 3-4 = 00 is not a valid month (01-12) -> rejected.
        // Note: the reference source's final "historical exception account" fallback
        // (see M57 javadoc) is unreachable for any input, since every possible value of
        // "first" (0-99) is already covered by an earlier branch in the dispatch chain -
        // this is a pre-existing quirk of the specification/reference source, not
        // something introduced by this reimplementation.
        assertThat(GermanCheckDigitMethod.M57.calculate(BLZ, "1500000000".toCharArray()).isValid()).isFalse();
    }

    @Test
    void calculate_b9_firstBranch_wrapPlusFiveRetry() {
        // "0012345673" is the direct match (crc == sum % 10); mutate it so the direct
        // check fails but the +5 wrap-around retry succeeds instead.
        CheckDigitResult direct = GermanCheckDigitMethod.B9.calculate(BLZ, "0012345673".toCharArray());
        assertThat(direct.isValid()).isTrue();

        char[] wrapped = "0012345673".toCharArray();
        wrapped[9] = (char) ('0' + (wrapped[9] - '0' + 5) % 10);
        CheckDigitResult viaWrap = GermanCheckDigitMethod.B9.calculate(BLZ, wrapped);
        assertThat(viaWrap.isValid()).isTrue();
    }

    @Test
    void calculate_b9_thirdBranch_rejectedOutright() {
        // digits 1-3 all non-zero: neither documented branch applies
        assertThat(GermanCheckDigitMethod.B9.calculate(BLZ, "1112345673".toCharArray()).isValid()).isFalse();
    }

    // getCode() / fromCode()

    @Test
    void code_hasNoMPrefix() {
        assertThat(GermanCheckDigitMethod.M00.getCode()).isEqualTo("00");
        assertThat(GermanCheckDigitMethod.M09.getCode()).isEqualTo("09");
    }

    @Test
    void code_letterCodes_returnedAsIs() {
        assertThat(GermanCheckDigitMethod.A0.getCode()).isEqualTo("A0");
        assertThat(GermanCheckDigitMethod.D9.getCode()).isEqualTo("D9");
    }

    @ParameterizedTest(name = "[{index}] {0}")
    @EnumSource(GermanCheckDigitMethod.class)
    void fromCode_everyEnumConstant_roundTrips(GermanCheckDigitMethod method) {
        assertThat(GermanCheckDigitMethod.fromCode(method.getCode())).isSameAs(method);
    }

    @Test
    void calculate_a4_variante2_fallsBackFromVariante1() {
        // fails Variante 1 (Modulus 11) but succeeds Variante 2 (Modulus 7) - Bundesbank test vector
        assertThat(GermanCheckDigitMethod.A4.calculate(BLZ, "0004711172".toCharArray()).isValid()).isTrue();
    }

    @Test
    void calculate_a4_digits3And4Are99_skipsToVariante3() {
        // Bundesbank test vector for Variante 3
        assertThat(GermanCheckDigitMethod.A4.calculate(BLZ, "1199503010".toCharArray()).isValid()).isTrue();
    }

    @Test
    void calculate_a4_digits3And4Are99_fallsBackToVariante4() {
        // fails Variante 3 but succeeds Variante 4 / M93 - Bundesbank test vector
        assertThat(GermanCheckDigitMethod.A4.calculate(BLZ, "1299503117".toCharArray()).isValid()).isTrue();
    }

    @Test
    void calculate_a4_digits3And4Are99_failsAllVariants() {
        // fails Variante 3 and Variante 4 alike - Bundesbank test vector
        assertThat(GermanCheckDigitMethod.A4.calculate(BLZ, "6099702031".toCharArray()).isValid()).isFalse();
    }

    @Test
    void calculate_b0_leadingZero_alwaysInvalid() {
        assertThat(GermanCheckDigitMethod.B0.calculate(BLZ, "0000000606".toCharArray()).isValid()).isFalse();
    }

    @Test
    void calculate_b0_leadingEight_alwaysInvalid() {
        assertThat(GermanCheckDigitMethod.B0.calculate(BLZ, "8137423260".toCharArray()).isValid()).isFalse();
    }

    @Test
    void calculate_b0_digit8InVarianteOneSet_notChecked() {
        // digit 8 (index 7) == 1 -> Variante 1 -> M09 - Bundesbank test vector
        CheckDigitResult result = GermanCheckDigitMethod.B0.calculate(BLZ, "1197423162".toCharArray());
        assertThat(result.isChecked()).isFalse();
    }

    @Test
    void fromCode_unknownCode_throwsIllegalArgumentException() {
        // "52" is deliberately not implemented (see class javadoc) - genuinely unknown to fromCode
        assertThatIllegalArgumentException()
            .isThrownBy(() -> GermanCheckDigitMethod.fromCode("52"))
            .withMessageContaining("52");
    }

    @Test
    void fromCode_unusedMethod12_throwsIllegalArgumentException() {
        assertThatIllegalArgumentException()
            .isThrownBy(() -> GermanCheckDigitMethod.fromCode("12"));
    }

    @Test
    void fromCode_null_throwsNullPointerException() {
        assertThatThrownBy(() -> GermanCheckDigitMethod.fromCode(null))
            .isInstanceOf(NullPointerException.class);
    }

}
