/*
 * Copyright © 2025-2026 Markus Spann, SpeedBankingDe
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.speedbanking.iban;

import static de.speedbanking.util.CharUtil.isAllDigitOrUpperCase;
import static de.speedbanking.util.CharUtil.isAllDigits;
import static de.speedbanking.util.CharUtil.isAllUpperCase;

/**
 * Container class for all country-specific {@link CountryValidator} implementations.
 *
 * <h3>Code generation</h3>
 * The inner classes are produced by {@code CountryValidatorCodeGenerator} and must
 * not be edited by hand.  The region between the {@code BGN} and {@code END} markers
 * below is overwritten on each generation run.
 * <p>
 * Countries <em>without</em> a National Check Digit extend {@link AbstractCountryValidator}
 * and contain only a {@code validateIban} implementation.<br>
 * Countries <em>with</em> a National Check Digit extend {@link AbstractNcdCountryValidator},
 * which wires the matching {@link NationalCheckDigitCalculator} inner class via the
 * self-reference pattern documented in {@link AbstractNcdCountryValidator}.
 *
 * @since 1.8.5
 *
 * @see CountryValidator
 * @see AbstractCountryValidator
 * @see AbstractNcdCountryValidator
 * @see NationalCheckDigitCalculators
 */
final class CountryValidators {

    /** Not instantiable. */
    private CountryValidators() {
        throw new UnsupportedOperationException(
            "Utility class " + getClass().getSimpleName() + " cannot be instantiated");
    }

    // --- BGN: generated by CountryValidatorCodeGenerator ---

    /** Validator for Andorra (AD), IBAN length: 24, BBAN pattern: {@code 4!n4!n12!c} */
    static final class AD extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 12);
        }
    }

    /** Validator for United Arab Emirates (AE), IBAN length: 23, BBAN pattern: {@code 3!n16!n} */
    static final class AE extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 23);
        }
    }

    /** NCD-aware Validator for Albania (AL), IBAN length: 28, BBAN pattern: {@code 8!n16!c} */
    static final class AL extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 12)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Angola (AO), IBAN length: 25, BBAN pattern: {@code 4!n4!n11!n2!n} */
    static final class AO extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 25)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Austria (AT), IBAN length: 20, BBAN pattern: {@code 5!n11!n} */
    static final class AT extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 20);
        }
    }

    /** Validator for Azerbaijan (AZ), IBAN length: 28, BBAN pattern: {@code 4!a20!c} */
    static final class AZ extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** NCD-aware Validator for Bosnia and Herzegovina (BA), IBAN length: 20, BBAN pattern: {@code 3!n3!n8!n2!n} */
    static final class BA extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 20)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Belgium (BE), IBAN length: 16, BBAN pattern: {@code 3!n7!n2!n} */
    static final class BE extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 16)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Bulgaria (BG), IBAN length: 22, BBAN pattern: {@code 4!a4!n2!n8!c} */
    static final class BG extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 14);
        }
    }

    /** Validator for Bahrain (BH), IBAN length: 22, BBAN pattern: {@code 4!a14!c} */
    static final class BH extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** Validator for Burundi (BI), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!n2!n} */
    static final class BI extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 27);
        }
    }

    /** Validator for Brazil (BR), IBAN length: 29, BBAN pattern: {@code 8!n5!n10!n1!a1!c} */
    static final class BR extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 27)
                && isAllUpperCase(iban, 27, 28);
        }
    }

    /** Validator for Belarus (BY), IBAN length: 28, BBAN pattern: {@code 4!c4!n16!c} */
    static final class BY extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 8, 12);
        }
    }

    /** Validator for Switzerland (CH), IBAN length: 21, BBAN pattern: {@code 5!n12!c} */
    static final class CH extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 9);
        }
    }

    /** Validator for Costa Rica (CR), IBAN length: 22, BBAN pattern: {@code 4!n14!n} */
    static final class CR extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 22);
        }
    }

    /** Validator for Cape Verde (CV), IBAN length: 25, BBAN pattern: {@code 4!n4!n13!c} */
    static final class CV extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 12);
        }
    }

    /** Validator for Cyprus (CY), IBAN length: 28, BBAN pattern: {@code 3!n5!n16!c} */
    static final class CY extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 12);
        }
    }

    /** Validator for Czechia (CZ), IBAN length: 24, BBAN pattern: {@code 4!n16!n} */
    static final class CZ extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 24);
        }
    }

    /** Validator for Germany (DE), IBAN length: 22, BBAN pattern: {@code 8!n10!n} */
    static final class DE extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 22);
        }
    }

    /** Validator for Djibouti (DJ), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!n2!n} */
    static final class DJ extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 27);
        }
    }

    /** Validator for Denmark (DK), IBAN length: 18, BBAN pattern: {@code 4!n9!n1!n} */
    static final class DK extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 18);
        }
    }

    /** Validator for Dominican Republic (DO), IBAN length: 28, BBAN pattern: {@code 4!c20!n} */
    static final class DO extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 8, 28);
        }
    }

    /** NCD-aware Validator for Estonia (EE), IBAN length: 20, BBAN pattern: {@code 2!n14!n} */
    static final class EE extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 20)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Egypt (EG), IBAN length: 29, BBAN pattern: {@code 4!n4!n17!n} */
    static final class EG extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 29);
        }
    }

    /** NCD-aware Validator for Spain (ES), IBAN length: 24, BBAN pattern: {@code 4!n4!n1!n1!n10!n} */
    static final class ES extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 24)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Finland (FI), IBAN length: 18, BBAN pattern: {@code 3!n11!n} */
    static final class FI extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 18)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Åland Islands (AX), IBAN length: 18, BBAN pattern: {@code 3!n11!n} */
    static final class AX extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 18)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Falkland Islands (FK), IBAN length: 18, BBAN pattern: {@code 2!a12!n} */
    static final class FK extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 6)
                && isAllDigits(iban, 6, 18);
        }
    }

    /** NCD-aware Validator for Faroe Islands (FO), IBAN length: 18, BBAN pattern: {@code 4!n9!n1!n} */
    static final class FO extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 18)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for France (FR), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class FR extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for French Guiana (GF), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class GF extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Guadeloupe (GP), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class GP extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Martinique (MQ), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class MQ extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Réunion (RE), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class RE extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for French Polynesia (PF), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class PF extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for French Southern Territories (TF), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class TF extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Mayotte (YT), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class YT extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for New Caledonia (NC), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class NC extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Saint Barthélemy (BL), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class BL extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Saint Martin (French part) (MF), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class MF extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Saint Pierre and Miquelon (PM), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class PM extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Wallis and Futuna Islands (WF), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class WF extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Gabon (GA), IBAN length: 27, BBAN pattern: {@code 5!n5!n13!c} */
    static final class GA extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14);
        }
    }

    /** Validator for United Kingdom (GB), IBAN length: 22, BBAN pattern: {@code 4!a6!n8!n} */
    static final class GB extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 22);
        }
    }

    /** Validator for Isle of Man (IM), IBAN length: 22, BBAN pattern: {@code 4!a6!n8!n} */
    static final class IM extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 22);
        }
    }

    /** Validator for Jersey (JE), IBAN length: 22, BBAN pattern: {@code 4!a6!n8!n} */
    static final class JE extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 22);
        }
    }

    /** Validator for Guernsey (GG), IBAN length: 22, BBAN pattern: {@code 4!a6!n8!n} */
    static final class GG extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 22);
        }
    }

    /** Validator for Georgia (GE), IBAN length: 22, BBAN pattern: {@code 2!a16!n} */
    static final class GE extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 6)
                && isAllDigits(iban, 6, 22);
        }
    }

    /** Validator for Gibraltar (GI), IBAN length: 23, BBAN pattern: {@code 4!a15!c} */
    static final class GI extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** Validator for Greenland (GL), IBAN length: 18, BBAN pattern: {@code 4!n9!n1!n} */
    static final class GL extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 18);
        }
    }

    /** Validator for Greece (GR), IBAN length: 27, BBAN pattern: {@code 3!n4!n16!c} */
    static final class GR extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 11);
        }
    }

    /** Validator for Guatemala (GT), IBAN length: 28, BBAN pattern: {@code 4!c20!c} */
    static final class GT extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigitOrUpperCase(iban, 4, 28);
        }
    }

    /** Validator for Honduras (HN), IBAN length: 28, BBAN pattern: {@code 4!a20!n} */
    static final class HN extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 28);
        }
    }

    /** Validator for Croatia (HR), IBAN length: 21, BBAN pattern: {@code 7!n10!n} */
    static final class HR extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 21);
        }
    }

    /** NCD-aware Validator for Hungary (HU), IBAN length: 28, BBAN pattern: {@code 3!n4!n1!n15!n1!n} */
    static final class HU extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 28)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Ireland (IE), IBAN length: 22, BBAN pattern: {@code 4!a6!n8!n} */
    static final class IE extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 22);
        }
    }

    /** Validator for Israel (IL), IBAN length: 23, BBAN pattern: {@code 3!n3!n13!n} */
    static final class IL extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 23);
        }
    }

    /** Validator for Iraq (IQ), IBAN length: 23, BBAN pattern: {@code 4!a3!n12!n} */
    static final class IQ extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 23);
        }
    }

    /** Validator for Islamic Republic of Iran (IR), IBAN length: 26, BBAN pattern: {@code 3!n19!n} */
    static final class IR extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 26);
        }
    }

    /** Validator for Iceland (IS), IBAN length: 26, BBAN pattern: {@code 4!n2!n6!n10!n} */
    static final class IS extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 26);
        }
    }

    /** NCD-aware Validator for Italy (IT), IBAN length: 27, BBAN pattern: {@code 1!a5!n5!n12!c} */
    static final class IT extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 5)
                && isAllDigits(iban, 5, 15)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Jordan (JO), IBAN length: 30, BBAN pattern: {@code 4!a4!n18!c} */
    static final class JO extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 12);
        }
    }

    /** Validator for Kuwait (KW), IBAN length: 30, BBAN pattern: {@code 4!a22!c} */
    static final class KW extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** Validator for Kazakhstan (KZ), IBAN length: 20, BBAN pattern: {@code 3!n13!c} */
    static final class KZ extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 7);
        }
    }

    /** Validator for Lebanon (LB), IBAN length: 28, BBAN pattern: {@code 4!n20!c} */
    static final class LB extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 8);
        }
    }

    /** Validator for Saint Lucia (LC), IBAN length: 32, BBAN pattern: {@code 4!a24!c} */
    static final class LC extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** Validator for Liechtenstein (LI), IBAN length: 21, BBAN pattern: {@code 5!n12!c} */
    static final class LI extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 9);
        }
    }

    /** Validator for Lithuania (LT), IBAN length: 20, BBAN pattern: {@code 5!n11!n} */
    static final class LT extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 20);
        }
    }

    /** Validator for Luxembourg (LU), IBAN length: 20, BBAN pattern: {@code 3!n13!c} */
    static final class LU extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 7);
        }
    }

    /** Validator for Latvia (LV), IBAN length: 21, BBAN pattern: {@code 4!a13!c} */
    static final class LV extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** Validator for Libya (LY), IBAN length: 25, BBAN pattern: {@code 3!n3!n15!n} */
    static final class LY extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 25);
        }
    }

    /** Validator for Morocco (MA), IBAN length: 28, BBAN pattern: {@code 3!n5!n16!n} */
    static final class MA extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 28);
        }
    }

    /** NCD-aware Validator for Monaco (MC), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!c2!n} */
    static final class MC extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 14)
                && isAllDigits(iban, 25, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Moldova (MD), IBAN length: 24, BBAN pattern: {@code 2!c18!c} */
    static final class MD extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigitOrUpperCase(iban, 4, 24);
        }
    }

    /** NCD-aware Validator for Montenegro (ME), IBAN length: 22, BBAN pattern: {@code 3!n13!n2!n} */
    static final class ME extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 22)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for North Macedonia (MK), IBAN length: 19, BBAN pattern: {@code 3!n10!c2!n} */
    static final class MK extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 7)
                && isAllDigits(iban, 17, 19)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Mongolia (MN), IBAN length: 20, BBAN pattern: {@code 4!n12!n} */
    static final class MN extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 20);
        }
    }

    /** NCD-aware Validator for Mauritania (MR), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!n2!n} */
    static final class MR extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Malta (MT), IBAN length: 31, BBAN pattern: {@code 4!a5!n18!c} */
    static final class MT extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 13);
        }
    }

    /** Validator for Mauritius (MU), IBAN length: 30, BBAN pattern: {@code 4!a2!n2!n12!n3!n3!a} */
    static final class MU extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 8, 27)
                && isAllUpperCase(iban, 4, 8)
                && isAllUpperCase(iban, 27, 30);
        }
    }

    /** NCD-aware Validator for Mozambique (MZ), IBAN length: 25, BBAN pattern: {@code 4!n4!n11!n2!n} */
    static final class MZ extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 25)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Nicaragua (NI), IBAN length: 28, BBAN pattern: {@code 4!a20!n} */
    static final class NI extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 28);
        }
    }

    /** Validator for Netherlands (NL), IBAN length: 18, BBAN pattern: {@code 4!a10!n} */
    static final class NL extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 18);
        }
    }

    /** NCD-aware Validator for Norway (NO), IBAN length: 15, BBAN pattern: {@code 4!n6!n1!n} */
    static final class NO extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 15)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Oman (OM), IBAN length: 23, BBAN pattern: {@code 3!n16!c} */
    static final class OM extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 7);
        }
    }

    /** Validator for Pakistan (PK), IBAN length: 24, BBAN pattern: {@code 4!a16!c} */
    static final class PK extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** NCD-aware Validator for Poland (PL), IBAN length: 28, BBAN pattern: {@code 8!n16!n} */
    static final class PL extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 28)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Palestine (PS), IBAN length: 29, BBAN pattern: {@code 4!a21!c} */
    static final class PS extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** NCD-aware Validator for Portugal (PT), IBAN length: 25, BBAN pattern: {@code 4!n4!n11!n2!n} */
    static final class PT extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 25)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Qatar (QA), IBAN length: 29, BBAN pattern: {@code 4!a21!c} */
    static final class QA extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** Validator for Romania (RO), IBAN length: 24, BBAN pattern: {@code 4!a16!c} */
    static final class RO extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8);
        }
    }

    /** NCD-aware Validator for Serbia (RS), IBAN length: 22, BBAN pattern: {@code 3!n13!n2!n} */
    static final class RS extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 22)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Russia (RU), IBAN length: 33, BBAN pattern: {@code 9!n5!n15!c} */
    static final class RU extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 18);
        }
    }

    /** Validator for Saudi Arabia (SA), IBAN length: 24, BBAN pattern: {@code 2!n18!c} */
    static final class SA extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 6);
        }
    }

    /** Validator for Seychelles (SC), IBAN length: 31, BBAN pattern: {@code 4!a2!n2!n16!n3!a} */
    static final class SC extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 8, 28)
                && isAllUpperCase(iban, 4, 8)
                && isAllUpperCase(iban, 28, 31);
        }
    }

    /** Validator for Sudan (SD), IBAN length: 18, BBAN pattern: {@code 2!n12!n} */
    static final class SD extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 18);
        }
    }

    /** Validator for Sweden (SE), IBAN length: 24, BBAN pattern: {@code 3!n16!n1!n} */
    static final class SE extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 24);
        }
    }

    /** NCD-aware Validator for Slovenia (SI), IBAN length: 19, BBAN pattern: {@code 2!n3!n8!n2!n} */
    static final class SI extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 19)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Slovakia (SK), IBAN length: 24, BBAN pattern: {@code 4!n6!n10!n} */
    static final class SK extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 24);
        }
    }

    /** NCD-aware Validator for San Marino (SM), IBAN length: 27, BBAN pattern: {@code 1!a5!n5!n12!c} */
    static final class SM extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 5)
                && isAllDigits(iban, 5, 15)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Somalia (SO), IBAN length: 23, BBAN pattern: {@code 4!n3!n12!n} */
    static final class SO extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 23);
        }
    }

    /** Validator for São Tomé und Príncipe (ST), IBAN length: 25, BBAN pattern: {@code 4!n4!n11!n2!n} */
    static final class ST extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 25);
        }
    }

    /** Validator for El Salvador (SV), IBAN length: 28, BBAN pattern: {@code 4!a20!n} */
    static final class SV extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 28);
        }
    }

    /** NCD-aware Validator for Timor-Leste (TL), IBAN length: 23, BBAN pattern: {@code 3!n14!n2!n} */
    static final class TL extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 23)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Tunisia (TN), IBAN length: 24, BBAN pattern: {@code 2!n3!n13!n2!n} */
    static final class TN extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 24)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Turkey (TR), IBAN length: 26, BBAN pattern: {@code 5!n1!n16!c} */
    static final class TR extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 10)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Ukraine (UA), IBAN length: 29, BBAN pattern: {@code 6!n19!c} */
    static final class UA extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 10);
        }
    }

    /** Validator for Vatican City State (VA), IBAN length: 22, BBAN pattern: {@code 3!n15!n} */
    static final class VA extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 22);
        }
    }

    /** Validator for Virgin Islands (VG), IBAN length: 24, BBAN pattern: {@code 4!a16!n} */
    static final class VG extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 24);
        }
    }

    /** NCD-aware Validator for Kosovo (XK), IBAN length: 20, BBAN pattern: {@code 4!n10!n2!n} */
    static final class XK extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 20)
                && validateNationalCheckDigit(iban);
        }
    }

    /** Validator for Yemen (YE), IBAN length: 30, BBAN pattern: {@code 4!a4!n18!c} */
    static final class YE extends AbstractCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllUpperCase(iban, 4, 8)
                && isAllDigits(iban, 8, 12);
        }
    }

    /** NCD-aware Validator for Burkina Faso (BF), IBAN length: 27, BBAN pattern: {@code 5!c5!n11!n2!n} */
    static final class BF extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 9, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Benin (BJ), IBAN length: 28, BBAN pattern: {@code 5!c5!n12!n2!n} */
    static final class BJ extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 9, 28)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Central African Republic (CF), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!n2!n} */
    static final class CF extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Cameroon (CM), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!n2!n} */
    static final class CM extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Algeria (DZ), IBAN length: 24, BBAN pattern: {@code 3!n5!n10!n2!n} */
    static final class DZ extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 24)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Equatorial Guinea (GQ), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!n2!n} */
    static final class GQ extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Comoros (KM), IBAN length: 27, BBAN pattern: {@code 5!n5!n11!n2!n} */
    static final class KM extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 4, 27)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Senegal (SN), IBAN length: 28, BBAN pattern: {@code 5!c5!n12!n2!n} */
    static final class SN extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 9, 28)
                && validateNationalCheckDigit(iban);
        }
    }

    /** NCD-aware Validator for Togo (TG), IBAN length: 28, BBAN pattern: {@code 5!c5!n12!n2!n} */
    static final class TG extends AbstractNcdCountryValidator {
        @Override
        public boolean validateIban(final char[] iban) {
            return isAllDigits(iban, 9, 28)
                && validateNationalCheckDigit(iban);
        }
    }

    // --- END: generated by CountryValidatorCodeGenerator ---
}
