/*
 * Copyright © 2025 Markus Spann, SpeedBankingDe
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.speedbanking.iban;

import de.speedbanking.iban.util.IbanPatternConverter;
import de.speedbanking.util.CountryUtil;
import de.speedbanking.util.IndexRange;

import java.lang.reflect.InvocationTargetException;
import java.time.YearMonth;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.StringJoiner;
import java.util.regex.Pattern;

/**
 * The definitive, immutable registry for all **ISO 13616-compliant national IBAN formats**.
 * <p>
 * This enumeration holds the official structural rules (total length, BBAN pattern, component index ranges)
 * for each country, as published in the **SWIFT IBAN Registry (Release 100 - Oct 2025)**.
 * <p>
 * The **International Organization for Standardization (ISO)** designated **SWIFT** as the
 * Registration Authority for ISO 13616.
 *
 * <p>
 * **BBAN Pattern Notation** (defined in ISO 13616):
 * <ul>
 *   <li>{@code n}: Digits (numeric characters 0-9)</li>
 *   <li>{@code a}: Upper-case letters (alphabetic characters A-Z)</li>
 *   <li>{@code c}: Upper-case letters and digits (alphanumeric characters A-Z and 0-9)</li>
 *   <li>{@code !}: Indicates fixed length (e.g., 4!n)</li>
 * </ul>
 *
 * Indexing is zero-based and exclusive of the end index (Java's substring convention).
 * Example: A position "1-4" in the registry (BBAN starts at char 0) becomes index 4 to 8 in the full IBAN string.
 *
 * @since 1.8.0
 */
public enum IbanRegistry {

    // --- Enum Constants (Generated by IbanRegistryCodeGenerator) ---

    /**
     * <strong>Andorra ({@code AD})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!n4!n12!c}<br>
     * Example: {@code AD1200012030200359100100}
     */
    AD(StructureData.builder().withIbanLength(24)
         .withBbanPattern("4!n4!n12!c")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 24))
         .build(),
       MetaData.of(
           "Andorra", true, "AD1200012030200359100100",
           YearMonth.of(2021, 3)),
       ContactData.of(
           "Associacio de Bancs Andorrans (ABA)", null, "C/ Ciutat de Consuegra, 16 Edifici l'Illa, esc. A, 2n pis",
           "AD500 Andorra la Vella Principat d'Andorra", "aba@aba.ad", "376 80 71 10")
    ),

    /**
     * <strong>United Arab Emirates ({@code AE})</strong><p>
     * IBAN Length: 23<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n16!n}<br>
     * Example: {@code AE070331234567890123456}
     */
    AE(StructureData.builder().withIbanLength(23)
         .withBbanPattern("3!n16!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 23))
         .build(),
       MetaData.of(
           "United Arab Emirates", false, "AE070331234567890123456",
           YearMonth.of(2025, 2)),
       ContactData.of(
           "Central Bank of the United Arab Emirates", null, "Bainuna Street, Al Bateen",
           "Abu Dhabi PO Box 854", null, null)
    ),

    /**
     * <strong>Albania ({@code AL})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 8!n16!c}<br>
     * Example: {@code AL47212110090000000235698741}
     */
    AL(StructureData.builder().withIbanLength(28)
         .withBbanPattern("8!n16!c")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("5!n", IndexRange.of(7, 11))
         .withAccountNumber(IndexRange.of(12, 28))
         .build(),
       MetaData.of(
           "Albania", false, "AL47212110090000000235698741",
           YearMonth.of(2025, 6)),
       ContactData.of(
           "Bank of Albania", "Payment systems", "Kompleksi Halili Rruga e Dibres",
           "1000 Tirana", null, null)
    ),

    /**
     * <strong>Angola ({@code AO})</strong><p>
     * IBAN Length: 25<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n4!n11!n2!n}<br>
     * Example: {@code AO06000600000100037131174}
     */
    AO(StructureData.builder().withIbanLength(25)
         .withBbanPattern("4!n4!n11!n2!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 23))
         .build(),
       MetaData.of(
           "Angola", false, "AO06000600000100037131174",
           null),
       null),

    /**
     * <strong>Austria ({@code AT})</strong><p>
     * IBAN Length: 20<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n11!n}<br>
     * Example: {@code AT611904300234573201}
     */
    AT(StructureData.builder().withIbanLength(20)
         .withBbanPattern("5!n11!n")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withAccountNumber(IndexRange.of(9, 20))
         .build(),
       MetaData.of(
           "Austria", true, "AT611904300234573201",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "PSA Payement Services Austria GMBH", "Account Systems", "Rivergate 2, Handelskai 92",
           "1200 Wien", "accountsystems@psa.at", "+ 43 15053280 / 0")
    ),

    /**
     * <strong>Azerbaijan ({@code AZ})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a20!c}<br>
     * Example: {@code AZ21NABZ00000000137010001944}
     */
    AZ(StructureData.builder().withIbanLength(28)
         .withBbanPattern("4!a20!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 28))
         .build(),
       MetaData.of(
           "Azerbaijan", false, "AZ21NABZ00000000137010001944",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Central Bank of the Republic of Azerbaijan", "Head Office", "32, R. Behbudov",
           "AZ 1014 Baku", "payment_systems@cbar.az", "+ 994 124931122")
    ),

    /**
     * <strong>Bosnia and Herzegovina ({@code BA})</strong><p>
     * IBAN Length: 20<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n3!n8!n2!n}<br>
     * Example: {@code BA391290079401028494}
     */
    BA(StructureData.builder().withIbanLength(20)
         .withBbanPattern("3!n3!n8!n2!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("3!n", IndexRange.of(7, 10))
         .withAccountNumber(IndexRange.of(10, 18))
         .build(),
       MetaData.of(
           "Bosnia and Herzegovina", false, "BA391290079401028494",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Centralna banka Bosne i Hercegovine", "Payment Systems Division", "25 Maršala Tita Street",
           "71000 Sarajevo, Bosnia and Herzegovina", null, null)
    ),

    /**
     * <strong>Belgium ({@code BE})</strong><p>
     * IBAN Length: 16<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n7!n2!n}<br>
     * Example: {@code BE68539007547034}
     */
    BE(StructureData.builder().withIbanLength(16)
         .withBbanPattern("3!n7!n2!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 14))
         .build(),
       MetaData.of(
           "Belgium", true, "BE68539007547034",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Febelfin", "Payments & Operations", "Aarlenstraat 82",
           "1040 Brussels", "info@febelfin.be", "+ 32 25076811")
    ),

    /**
     * <strong>Bulgaria ({@code BG})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a4!n2!n8!c}<br>
     * Example: {@code BG80BNBG96611020345678}
     */
    BG(StructureData.builder().withIbanLength(22)
         .withBbanPattern("4!a4!n2!n8!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(14, 22))
         .build(),
       MetaData.of(
           "Bulgaria", true, "BG80BNBG96611020345678",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Bulgarian National Bank", "Payment Systems and Minimum Reserves Directorate", "1, Knyaz Alexander I Sq.",
           "1000 Sofia, Bulgaria", "rtgs@bnbank.org", "+ 359 29145761")
    ),

    /**
     * <strong>Bahrain ({@code BH})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a14!c}<br>
     * Example: {@code BH67BMAG00001299123456}
     */
    BH(StructureData.builder().withIbanLength(22)
         .withBbanPattern("4!a14!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 22))
         .build(),
       MetaData.of(
           "Bahrain", false, "BH67BMAG00001299123456",
           YearMonth.of(2012, 1)),
       ContactData.of(
           "Central Bank of Bahrain", "Banking Services Directorate", "King Faisal Highway, Block 317, Road 1702, Building 96",
           "Manama", null, null)
    ),

    /**
     * <strong>Burundi ({@code BI})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 5!n5!n11!n2!n}<br>
     * Example: {@code BI4210000100010000332045181}
     */
    BI(StructureData.builder().withIbanLength(27)
         .withBbanPattern("5!n5!n11!n2!n")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withBranchCode("5!n", IndexRange.of(9, 14))
         .withAccountNumber(IndexRange.of(14, 27))
         .build(),
       MetaData.of(
           "Burundi", false, "BI4210000100010000332045181",
           YearMonth.of(2021, 10)),
       ContactData.of(
           "Banque de la Republique du Burundi", null, "1, Avenue du Gouvernement PO BOX 705",
           "Bujumbura", "brb@brb.bi", null)
    ),

    /**
     * <strong>Brazil ({@code BR})</strong><p>
     * IBAN Length: 29<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 8!n5!n10!n1!a1!c}<br>
     * Example: {@code BR1800360305000010009795493C1}
     */
    BR(StructureData.builder().withIbanLength(29)
         .withBbanPattern("8!n5!n10!n1!a1!c")
         .withBankCode("8!n", IndexRange.of(4, 12))
         .withBranchCode("5!n", IndexRange.of(12, 17))
         .withAccountNumber(IndexRange.of(17, 27))
         .build(),
       MetaData.of(
           "Brazil", false, "BR1800360305000010009795493C1",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Banco Central do Brasil", "DEBAN - Departamento de Operações Bancárias e de Sistema de Pagamentos", "SBS Quadra 3 Bloco B",
           "71.070-900 Brasília", "iban@bcb.gov.br", "+ 55 (61)34142666 / + 55 (51)32157339")
    ),

    /**
     * <strong>Belarus ({@code BY})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!c4!n16!c}<br>
     * Example: {@code BY13NBRB3600900000002Z00AB00}
     */
    BY(StructureData.builder().withIbanLength(28)
         .withBbanPattern("4!c4!n16!c")
         .withBankCode("4!c", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 28))
         .build(),
       MetaData.of(
           "Belarus", false, "BY13NBRB3600900000002Z00AB00",
           YearMonth.of(2024, 2)),
       ContactData.of(
           "National Bank of the Republic of Belarus", "Payment system and digital technologies directorate", "Nezavisimosty Avenue, 20",
           "220008 Minsk", null, null)
    ),

    /**
     * <strong>Switzerland ({@code CH})</strong><p>
     * IBAN Length: 21<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n12!c}<br>
     * Example: {@code CH9300762011623852957}
     */
    CH(StructureData.builder().withIbanLength(21)
         .withBbanPattern("5!n12!c")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withAccountNumber(IndexRange.of(9, 21))
         .build(),
       MetaData.of(
           "Switzerland", true, "CH9300762011623852957",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "SIX Interbank Clearing Ltd", "Zentrale Koordinationsstelle fuer IBAN/IPI - Technical Support", "Hardturmstrasse 201",
           "CH-8021 ZURICH", "iban@six-group.com", "+ 41 583994420")
    ),

    /**
     * <strong>Costa Rica ({@code CR})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n14!n}<br>
     * Example: {@code CR05015202001026284066}
     */
    CR(StructureData.builder().withIbanLength(22)
         .withBbanPattern("4!n14!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 22))
         .build(),
       MetaData.of(
           "Costa Rica", false, "CR05015202001026284066",
           YearMonth.of(2019, 1)),
       ContactData.of(
           "Banco Central de Costa Rica", "Sistema de Pagos", "Avenida Central y 1a. Calles 2 y 4",
           "10058-1000 San José", null, null)
    ),

    /**
     * <strong>Cape Verde ({@code CV})</strong><p>
     * IBAN Length: 25<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n4!n13!c}<br>
     * Example: {@code CV05123412341234123412341}
     */
    CV(StructureData.builder().withIbanLength(25)
         .withBbanPattern("4!n4!n13!c")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 25))
         .build(),
       MetaData.of(
           "Cape Verde", false, "CV05123412341234123412341",
           null),
       null),

    /**
     * <strong>Cyprus ({@code CY})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n5!n16!c}<br>
     * Example: {@code CY17002001280000001200527600}
     */
    CY(StructureData.builder().withIbanLength(28)
         .withBbanPattern("3!n5!n16!c")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("5!n", IndexRange.of(7, 12))
         .withAccountNumber(IndexRange.of(12, 28))
         .build(),
       MetaData.of(
           "Cyprus", true, "CY17002001280000001200527600",
           YearMonth.of(2009, 8)),
       ContactData.of(
           "Central Bank of Cyprus", "Payment systems and Accounting Services", "80 Kennedy Avenue",
           "P.O. Box 25529 CY-1395 Nicosia", "PaymentSystems@centralbank.gov.cy", null)
    ),

    /**
     * <strong>Czechia ({@code CZ})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!n16!n}<br>
     * Example: {@code CZ6508000000192000145399}
     */
    CZ(StructureData.builder().withIbanLength(24)
         .withBbanPattern("4!n16!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 24))
         .build(),
       MetaData.of(
           "Czechia", true, "CZ6508000000192000145399",
           YearMonth.of(2025, 6)),
       ContactData.of(
           "Czech National Bank", "Cash and Payments Department", "Na Příkopě 28",
           "Praha 1", "iban.info@cnb.cz", null)
    ),

    /**
     * <strong>Germany ({@code DE})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 8!n10!n}<br>
     * Example: {@code DE89370400440532013000}
     */
    DE(StructureData.builder().withIbanLength(22)
         .withBbanPattern("8!n10!n")
         .withBankCode("8!n", IndexRange.of(4, 12))
         .withAccountNumber(IndexRange.of(12, 22))
         .build(),
       MetaData.of(
           "Germany", true, "DE89370400440532013000",
           YearMonth.of(2011, 1)),
       ContactData.of(
           "Bundesverband deutscher Banken", null, "Burgstraße 28",
           "10178 Berlin", "iban@bdb.de", "+ 49 3016632301")
    ),

    /**
     * <strong>Djibouti ({@code DJ})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 5!n5!n11!n2!n}<br>
     * Example: {@code DJ2100010000000154000100186}
     */
    DJ(StructureData.builder().withIbanLength(27)
         .withBbanPattern("5!n5!n11!n2!n")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withBranchCode("5!n", IndexRange.of(9, 14))
         .withAccountNumber(IndexRange.of(14, 25))
         .build(),
       MetaData.of(
           "Djibouti", false, "DJ2100010000000154000100186",
           YearMonth.of(2022, 5)),
       ContactData.of(
           "Banque Centrale de Djibouti", null, "Avenue Cheick Osman P.O Box 705",
           "Djibouti", "bndj@intnet.dj", null)
    ),

    /**
     * <strong>Denmark ({@code DK})</strong><p>
     * IBAN Length: 18<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!n9!n1!n}<br>
     * Example: {@code DK5000400440116243}
     */
    DK(StructureData.builder().withIbanLength(18)
         .withBbanPattern("4!n9!n1!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 18))
         .build(),
       MetaData.of(
           "Denmark", true, "DK5000400440116243",
           YearMonth.of(2018, 11)),
       ContactData.of(
           "Finance Denmark", null, "7 Amaliegade",
           "DK 1256 Copenhagen K", "IBAN@FIDA.dk", null)
    ),

    /**
     * <strong>Dominican Republic ({@code DO})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!c20!n}<br>
     * Example: {@code DO28BAGR00000001212453611324}
     */
    DO(StructureData.builder().withIbanLength(28)
         .withBbanPattern("4!c20!n")
         .withBankCode("4!c", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 28))
         .build(),
       MetaData.of(
           "Dominican Republic", false, "DO28BAGR00000001212453611324",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Central Bank of the Dominican Republic", "Payment Systems", "Av. Pedro Henríquez Urena esq. Leopoldo Navarro",
           "Santo Domingo", "sistema.pagos@bancentral.gov.do", "+ 1 8092219111 (ext. 3409)")
    ),

    /**
     * <strong>Estonia ({@code EE})</strong><p>
     * IBAN Length: 20<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 2!n14!n}<br>
     * Example: {@code EE382200221020145685}
     */
    EE(StructureData.builder().withIbanLength(20)
         .withBbanPattern("2!n14!n")
         .withBankCode("2!n", IndexRange.of(4, 6))
         .withBranchCode("2!n", IndexRange.of(6, 8))
         .withAccountNumber(IndexRange.of(8, 19))
         .build(),
       MetaData.of(
           "Estonia", true, "EE382200221020145685",
           YearMonth.of(2024, 12)),
       ContactData.of(
           "Estonian Banking Association", null, "Maakri 30",
           "10145 Tallinn", "pangaliit@pangaliit.ee", "+ 372 6116569")
    ),

    /**
     * <strong>Egypt ({@code EG})</strong><p>
     * IBAN Length: 29<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n4!n17!n}<br>
     * Example: {@code EG380019000500000000263180002}
     */
    EG(StructureData.builder().withIbanLength(29)
         .withBbanPattern("4!n4!n17!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 29))
         .build(),
       MetaData.of(
           "Egypt", false, "EG380019000500000000263180002",
           YearMonth.of(2020, 1)),
       ContactData.of(
           "Central Bank of Egypt", "Operations Sector", "54 El Gomherya street",
           "Cairo", "Operations.development@cbe.org.eg", "+ 20 16777 (ext. 3109)")
    ),

    /**
     * <strong>Spain ({@code ES})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!n4!n1!n1!n10!n}<br>
     * Example: {@code ES9121000418450200051332}
     */
    ES(StructureData.builder().withIbanLength(24)
         .withBbanPattern("4!n4!n1!n1!n10!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(14, 24))
         .build(),
       MetaData.of(
           "Spain", true, "ES9121000418450200051332",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Asociación Española de Banca Privada (AEB)", null, "C/ Velázquez, 64 – 66",
           "28001 Madrid", "asesoria.pagos@aebanca.es", "+ 34 917891311")
    ),

    /**
     * <strong>Finland ({@code FI})</strong><p>
     * IBAN Length: 18<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n11!n}<br>
     * Example: {@code FI2112345600000785}
     */
    FI(StructureData.builder().withIbanLength(18)
         .withBbanPattern("3!n11!n")
         .withBankCode("6!n", IndexRange.of(4, 10))
         .withAccountNumber(IndexRange.of(10, 17))
         .build(),
       MetaData.of(
           "Finland", true, "FI2112345600000785",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Federation of Finnish Financial Services", null, "PO Box 1009",
           "FIN-00101 Helsinki", "paymentsupport@finanssiala.fi", null)
    ),

    /**
     * <strong>Aland Islands ({@code AX})</strong><p>
     * IBAN Length: 18<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n11!n}<br>
     * Example: {@code FI2112345600000785}
     */
    AX("Aland Islands", FI),

    /**
     * <strong>Falkland Islands ({@code FK})</strong><p>
     * IBAN Length: 18<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 2!a12!n}<br>
     * Example: {@code FK88SC123456789012}
     */
    FK(StructureData.builder().withIbanLength(18)
         .withBbanPattern("2!a12!n")
         .withBankCode("2!a", IndexRange.of(4, 6))
         .withAccountNumber(IndexRange.of(6, 18))
         .build(),
       MetaData.of(
           "Falkland Islands", false, "FK88SC123456789012",
           YearMonth.of(2023, 7)),
       ContactData.of(
           "Falkland Islands Government", "The Treasury", "Thatcher Drive",
           "FIQQ 1ZZ Stanley", "treasury@sec.gov.fk", null)
    ),

    /**
     * <strong>Faroe Islands ({@code FO})</strong><p>
     * IBAN Length: 18<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n9!n1!n}<br>
     * Example: {@code FO6264600001631634}
     */
    FO(StructureData.builder().withIbanLength(18)
         .withBbanPattern("4!n9!n1!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 17))
         .build(),
       MetaData.of(
           "Faroe Islands", false, "FO6264600001631634",
           YearMonth.of(2017, 2)),
       ContactData.of(
           "Finance Denmark", null, "7 Amaliegade",
           "DK 1256 Copenhagen K", "IBAN@FIDA.dk", null)
    ),

    /**
     * <strong>France ({@code FR})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    FR(StructureData.builder().withIbanLength(27)
         .withBbanPattern("5!n5!n11!c2!n")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withBranchCode("5!n", IndexRange.of(9, 14))
         .withAccountNumber(IndexRange.of(14, 25))
         .build(),
       MetaData.of(
           "France", true, "FR1420041010050500013M02606",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "CFONB", null, "18 rue la Fayette",
           "75009 Paris", "cfonb@cfonb.fr", "+ 33 148005042")
    ),

    /**
     * <strong>French Guiana ({@code GF})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    GF("French Guiana", FR),

    /**
     * <strong>Guadeloupe ({@code GP})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    GP("Guadeloupe", FR),

    /**
     * <strong>Martinique ({@code MQ})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    MQ("Martinique", FR),

    /**
     * <strong>Réunion ({@code RE})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    RE("Réunion", FR),

    /**
     * <strong>French Polynesia ({@code PF})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    PF("French Polynesia", FR),

    /**
     * <strong>French Southern Territories ({@code TF})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    TF("French Southern Territories", FR),

    /**
     * <strong>Mayotte ({@code YT})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    YT("Mayotte", FR),

    /**
     * <strong>New Caledonia ({@code NC})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    NC("New Caledonia", FR),

    /**
     * <strong>Saint Barthélemy ({@code BL})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    BL("Saint Barthélemy", FR),

    /**
     * <strong>Saint Martin (French part) ({@code MF})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    MF("Saint Martin (French part)", FR),

    /**
     * <strong>Saint Pierre and Miquelon ({@code PM})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    PM("Saint Pierre and Miquelon", FR),

    /**
     * <strong>Wallis and Futuna Islands ({@code WF})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code FR1420041010050500013M02606}
     */
    WF("Wallis and Futuna Islands", FR),

    /**
     * <strong>Gabon ({@code GA})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 5!n5!n13!c}<br>
     * Example: {@code GA2140021010032001890020126}
     */
    GA(StructureData.builder().withIbanLength(27)
         .withBbanPattern("5!n5!n13!c")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withBranchCode("5!n", IndexRange.of(9, 14))
         .withAccountNumber(IndexRange.of(14, 27))
         .build(),
       MetaData.of(
           "Gabon", false, "GA2140021010032001890020126",
           null),
       null),

    /**
     * <strong>United Kingdom ({@code GB})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a6!n8!n}<br>
     * Example: {@code GB29NWBK60161331926819}
     */
    GB(StructureData.builder().withIbanLength(22)
         .withBbanPattern("4!a6!n8!n")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withBranchCode("6!n", IndexRange.of(8, 14))
         .withAccountNumber(IndexRange.of(14, 22))
         .build(),
       MetaData.of(
           "United Kingdom", true, "GB29NWBK60161331926819",
           YearMonth.of(2017, 5)),
       ContactData.of(
           "Payments UK Management Ltd", "International Standards and Services", "14 Finsbury Square",
           "London EC2A 1LQ", null, null)
    ),

    /**
     * <strong>Isle of Man ({@code IM})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a6!n8!n}<br>
     * Example: {@code GB29NWBK60161331926819}
     */
    IM("Isle of Man", GB),

    /**
     * <strong>Jersey ({@code JE})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a6!n8!n}<br>
     * Example: {@code GB29NWBK60161331926819}
     */
    JE("Jersey", GB),

    /**
     * <strong>Guernsey ({@code GG})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a6!n8!n}<br>
     * Example: {@code GB29NWBK60161331926819}
     */
    GG("Guernsey", GB),

    /**
     * <strong>Georgia ({@code GE})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 2!a16!n}<br>
     * Example: {@code GE29NB0000000101904917}
     */
    GE(StructureData.builder().withIbanLength(22)
         .withBbanPattern("2!a16!n")
         .withBankCode("2!a", IndexRange.of(4, 6))
         .withAccountNumber(IndexRange.of(6, 22))
         .build(),
       MetaData.of(
           "Georgia", false, "GE29NB0000000101904917",
           YearMonth.of(2023, 4)),
       ContactData.of(
           "National Bank of Georgia", "Payment Systems", "1, Zviad Gamsakhurdia Embankment",
           "0114 Tbilisi", "RTGS@nbg.gov.ge", "+ 995 322406555")
    ),

    /**
     * <strong>Gibraltar ({@code GI})</strong><p>
     * IBAN Length: 23<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a15!c}<br>
     * Example: {@code GI75NWBK000000007099453}
     */
    GI(StructureData.builder().withIbanLength(23)
         .withBbanPattern("4!a15!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 23))
         .build(),
       MetaData.of(
           "Gibraltar", true, "GI75NWBK000000007099453",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Financial Services Commission", null, "PO Box 940",
           "Suite 3, Ground Floor, Atlantic Suites", "info@fsc.gi", "+350 20040283")
    ),

    /**
     * <strong>Greenland ({@code GL})</strong><p>
     * IBAN Length: 18<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n9!n1!n}<br>
     * Example: {@code GL8964710001000206}
     */
    GL(StructureData.builder().withIbanLength(18)
         .withBbanPattern("4!n9!n1!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 18))
         .build(),
       MetaData.of(
           "Greenland", false, "GL8964710001000206",
           YearMonth.of(2017, 2)),
       ContactData.of(
           "Finance Denmark", null, "7 Amaliegade",
           "DK 1256 Copenhagen K", "IBAN@FIDA.dk", null)
    ),

    /**
     * <strong>Greece ({@code GR})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n4!n16!c}<br>
     * Example: {@code GR1601101250000000012300695}
     */
    GR(StructureData.builder().withIbanLength(27)
         .withBbanPattern("3!n4!n16!c")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("4!n", IndexRange.of(7, 11))
         .withAccountNumber(IndexRange.of(11, 27))
         .build(),
       MetaData.of(
           "Greece", true, "GR1601101250000000012300695",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Hellenic Bank Association", "Payment Systems", "Amerikis 21A",
           "10672 Athens", "hba@hba.gr", "+ 30 2103386500")
    ),

    /**
     * <strong>Guatemala ({@code GT})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!c20!c}<br>
     * Example: {@code GT82TRAJ01020000001210029690}
     */
    GT(StructureData.builder().withIbanLength(28)
         .withBbanPattern("4!c20!c")
         .withBankCode("4!c", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 28))
         .build(),
       MetaData.of(
           "Guatemala", false, "GT82TRAJ01020000001210029690",
           YearMonth.of(2016, 10)),
       ContactData.of(
           "Banco de Guatemala", "Accounting and Payment System", "7 Avenue 22-01 Zone 1",
           "01001 Guatemala", "contabilidad@banguat.gob.gt", "(502) 2429-6000 EXT. 4300 (502) 2253-5352")
    ),

    /**
     * <strong>Honduras ({@code HN})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a20!n}<br>
     * Example: {@code HN88CABF00000000000250005469}
     */
    HN(StructureData.builder().withIbanLength(28)
         .withBbanPattern("4!a20!n")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 28))
         .build(),
       MetaData.of(
           "Honduras", false, "HN88CABF00000000000250005469",
           YearMonth.of(2024, 12)),
       ContactData.of(
           "Banco Central de Honduras", null, "Centro Cívico Gubernamental, Boulevard Fuerzas Armadas",
           "Tegucigalpa, MDC 3165", "carlos.avila@bch.hn", null)
    ),

    /**
     * <strong>Croatia ({@code HR})</strong><p>
     * IBAN Length: 21<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 7!n10!n}<br>
     * Example: {@code HR1210010051863000160}
     */
    HR(StructureData.builder().withIbanLength(21)
         .withBbanPattern("7!n10!n")
         .withBankCode("7!n", IndexRange.of(4, 11))
         .withAccountNumber(IndexRange.of(11, 21))
         .build(),
       MetaData.of(
           "Croatia", true, "HR1210010051863000160",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Croatian National Bank", "Payment Operations Area", "Trg hrvatskih velikana 3",
           "Zagreb / 10002", "zpp@hnb.hr", "+ 385 14564992")
    ),

    /**
     * <strong>Hungary ({@code HU})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n4!n1!n15!n1!n}<br>
     * Example: {@code HU42117730161111101800000000}
     */
    HU(StructureData.builder().withIbanLength(28)
         .withBbanPattern("3!n4!n1!n15!n1!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("4!n", IndexRange.of(7, 11))
         .withAccountNumber(IndexRange.of(11, 27))
         .build(),
       MetaData.of(
           "Hungary", true, "HU42117730161111101800000000",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Hungarian Banking Association", null, "József nádor tér 5-6",
           "H-1051 Budapest", "hba@hba.org.hu", "+ 36 13276030")
    ),

    /**
     * <strong>Ireland ({@code IE})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a6!n8!n}<br>
     * Example: {@code IE29AIBK93115212345678}
     */
    IE(StructureData.builder().withIbanLength(22)
         .withBbanPattern("4!a6!n8!n")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withBranchCode("6!n", IndexRange.of(8, 14))
         .withAccountNumber(IndexRange.of(14, 22))
         .build(),
       MetaData.of(
           "Ireland", true, "IE29AIBK93115212345678",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Banking & Payments Federation Ireland", null, "Floor 3 One Molesworth Street",
           "Dublin 2 D02 RF29", "info@bpfi.ie", null)
    ),

    /**
     * <strong>Israel ({@code IL})</strong><p>
     * IBAN Length: 23<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n3!n13!n}<br>
     * Example: {@code IL620108000000099999999}
     */
    IL(StructureData.builder().withIbanLength(23)
         .withBbanPattern("3!n3!n13!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("3!n", IndexRange.of(7, 10))
         .withAccountNumber(IndexRange.of(10, 23))
         .build(),
       MetaData.of(
           "Israel", false, "IL620108000000099999999",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Bank of Israel", "Payment and Settlement Systems", "Kaplan Street, Kyriat Ben Gurion",
           "91007 Jerusalem", "zahav@boi.org.il", "+ 972 26552020")
    ),

    /**
     * <strong>Iraq ({@code IQ})</strong><p>
     * IBAN Length: 23<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a3!n12!n}<br>
     * Example: {@code IQ98NBIQ850123456789012}
     */
    IQ(StructureData.builder().withIbanLength(23)
         .withBbanPattern("4!a3!n12!n")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withBranchCode("3!n", IndexRange.of(8, 11))
         .withAccountNumber(IndexRange.of(11, 23))
         .build(),
       MetaData.of(
           "Iraq", false, "IQ98NBIQ850123456789012",
           YearMonth.of(2016, 11)),
       ContactData.of(
           "Central Bank of Iraq", "SWIFT Department", "Rasheed Street",
           "Baghdad", "cbi@cbi.iq", "+ 964 47903737479")
    ),

    /**
     * <strong>Islamic Republic of Iran ({@code IR})</strong><p>
     * IBAN Length: 26<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n19!n}<br>
     * Example: {@code IR062960000000100324200001}
     */
    IR(StructureData.builder().withIbanLength(26)
         .withBbanPattern("3!n19!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 26))
         .build(),
       MetaData.of(
           "Islamic Republic of Iran", false, "IR062960000000100324200001",
           null),
       null),

    /**
     * <strong>Iceland ({@code IS})</strong><p>
     * IBAN Length: 26<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!n2!n6!n10!n}<br>
     * Example: {@code IS140159260076545510730339}
     */
    IS(StructureData.builder().withIbanLength(26)
         .withBbanPattern("4!n2!n6!n10!n")
         .withBankCode("2!n", IndexRange.of(4, 6))
         .withBranchCode("2!n", IndexRange.of(6, 8))
         .withAccountNumber(IndexRange.of(10, 16))
         .build(),
       MetaData.of(
           "Iceland", true, "IS140159260076545510730339",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Icelandic Banks Data Centre", null, "Katrinartun 2",
           "105 Reykjavik", "hjalp@rb.is", "+ 354 5698877")
    ),

    /**
     * <strong>Italy ({@code IT})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 1!a5!n5!n12!c}<br>
     * Example: {@code IT60X0542811101000000123456}
     */
    IT(StructureData.builder().withIbanLength(27)
         .withBbanPattern("1!a5!n5!n12!c")
         .withBankCode("5!n", IndexRange.of(5, 10))
         .withBranchCode("5!n", IndexRange.of(10, 15))
         .withAccountNumber(IndexRange.of(15, 27))
         .build(),
       MetaData.of(
           "Italy", true, "IT60X0542811101000000123456",
           YearMonth.of(2013, 3)),
       ContactData.of(
           "Associazione Bancaria Italiana", "Head of Payment Systems and Services", "Via delle Botteghe Oscure, 46",
           "00186 Rome – Italy", null, null)
    ),

    /**
     * <strong>Jordan ({@code JO})</strong><p>
     * IBAN Length: 30<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a4!n18!c}<br>
     * Example: {@code JO94CBJO0010000000000131000302}
     */
    JO(StructureData.builder().withIbanLength(30)
         .withBbanPattern("4!a4!n18!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 30))
         .build(),
       MetaData.of(
           "Jordan", false, "JO94CBJO0010000000000131000302",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Central Bank of Jordan", "Financial", "King Hussein Street",
           "11118 Amman – Capital", "finance@cbj.gov.jo", null)
    ),

    /**
     * <strong>Kuwait ({@code KW})</strong><p>
     * IBAN Length: 30<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a22!c}<br>
     * Example: {@code KW81CBKU0000000000001234560101}
     */
    KW(StructureData.builder().withIbanLength(30)
         .withBbanPattern("4!a22!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 30))
         .build(),
       MetaData.of(
           "Kuwait", false, "KW81CBKU0000000000001234560101",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Central Bank of Kuwait", "Information Technology and Banking Operations Sector", "P.O. Box 526 Safat",
           "13006 Safat", "bito@cbk.gov.kw", null)
    ),

    /**
     * <strong>Kazakhstan ({@code KZ})</strong><p>
     * IBAN Length: 20<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n13!c}<br>
     * Example: {@code KZ86125KZT5004100100}
     */
    KZ(StructureData.builder().withIbanLength(20)
         .withBbanPattern("3!n13!c")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 20))
         .build(),
       MetaData.of(
           "Kazakhstan", false, "KZ86125KZT5004100100",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "National Bank of the Republic of Kazakhstan", "Payment Systems", "21, Koktem-3",
           "050040 Almaty", null, null)
    ),

    /**
     * <strong>Lebanon ({@code LB})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n20!c}<br>
     * Example: {@code LB62099900000001001901229114}
     */
    LB(StructureData.builder().withIbanLength(28)
         .withBbanPattern("4!n20!c")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 28))
         .build(),
       MetaData.of(
           "Lebanon", false, "LB62099900000001001901229114",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Banque du Liban", "Payment Systems", "Masraf Lubnan street",
           "11-5544 Beirut", "IBAN@bdl.gov.lb", "+961-1-343317")
    ),

    /**
     * <strong>Saint Lucia ({@code LC})</strong><p>
     * IBAN Length: 32<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a24!c}<br>
     * Example: {@code LC55HEMM000100010012001200023015}
     */
    LC(StructureData.builder().withIbanLength(32)
         .withBbanPattern("4!a24!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 32))
         .build(),
       MetaData.of(
           "Saint Lucia", false, "LC55HEMM000100010012001200023015",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Saint Lucia Bureau of Standards", null, "Bisee Industrial Estate",
           "Castries, PO Box CP 5412", "slbs@candw.lc; info@slbs.org", null)
    ),

    /**
     * <strong>Liechtenstein ({@code LI})</strong><p>
     * IBAN Length: 21<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n12!c}<br>
     * Example: {@code LI21088100002324013AA}
     */
    LI(StructureData.builder().withIbanLength(21)
         .withBbanPattern("5!n12!c")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withAccountNumber(IndexRange.of(9, 21))
         .build(),
       MetaData.of(
           "Liechtenstein", true, "LI21088100002324013AA",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Liechtenstein Bankers Association", null, "P.O. Box 254",
           "9490 Vaduz", null, null)
    ),

    /**
     * <strong>Lithuania ({@code LT})</strong><p>
     * IBAN Length: 20<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n11!n}<br>
     * Example: {@code LT121000011101001000}
     */
    LT(StructureData.builder().withIbanLength(20)
         .withBbanPattern("5!n11!n")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withAccountNumber(IndexRange.of(9, 20))
         .build(),
       MetaData.of(
           "Lithuania", true, "LT121000011101001000",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Bank of Lithuania", "Operations and Payments Department", "Gedimino pr. 6",
           "Vilnius, LT-01103", "tarpbank@lb.lt", "+ 370 52680604")
    ),

    /**
     * <strong>Luxembourg ({@code LU})</strong><p>
     * IBAN Length: 20<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n13!c}<br>
     * Example: {@code LU280019400644750000}
     */
    LU(StructureData.builder().withIbanLength(20)
         .withBbanPattern("3!n13!c")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 20))
         .build(),
       MetaData.of(
           "Luxembourg", true, "LU280019400644750000",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "ABBL - Association des Banques et Banquiers Luxembourg", null, "Boîte Postale 13",
           "L-2010 Luxembourg", null, null)
    ),

    /**
     * <strong>Latvia ({@code LV})</strong><p>
     * IBAN Length: 21<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a13!c}<br>
     * Example: {@code LV80BANK0000435195001}
     */
    LV(StructureData.builder().withIbanLength(21)
         .withBbanPattern("4!a13!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 21))
         .build(),
       MetaData.of(
           "Latvia", true, "LV80BANK0000435195001",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Bank of Latvia", "Payment Systems", "K. Valdemāra 2A",
           "Riga, LV-1050", null, null)
    ),

    /**
     * <strong>Libya ({@code LY})</strong><p>
     * IBAN Length: 25<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n3!n15!n}<br>
     * Example: {@code LY83002048000020100120361}
     */
    LY(StructureData.builder().withIbanLength(25)
         .withBbanPattern("3!n3!n15!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("3!n", IndexRange.of(7, 10))
         .withAccountNumber(IndexRange.of(10, 25))
         .build(),
       MetaData.of(
           "Libya", false, "LY83002048000020100120361",
           YearMonth.of(2020, 9)),
       ContactData.of(
           "Central Bank of Libya", "Payment and Settlement Department", "Alfatah Road",
           "1103 Tripoli", "info@cbl.gov.ly", "+218 912137654")
    ),

    /**
     * <strong>Morocco ({@code MA})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n5!n16!n}<br>
     * Example: {@code MA64360815000001793222001617}
     */
    MA(StructureData.builder().withIbanLength(28)
         .withBbanPattern("3!n5!n16!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("5!n", IndexRange.of(7, 12))
         .withAccountNumber(IndexRange.of(12, 28))
         .build(),
       MetaData.of(
           "Morocco", false, "MA64360815000001793222001617",
           null),
       null),

    /**
     * <strong>Monaco ({@code MC})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 5!n5!n11!c2!n}<br>
     * Example: {@code MC5811222000010123456789030}
     */
    MC(StructureData.builder().withIbanLength(27)
         .withBbanPattern("5!n5!n11!c2!n")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withBranchCode("5!n", IndexRange.of(9, 14))
         .withAccountNumber(IndexRange.of(14, 25))
         .build(),
       MetaData.of(
           "Monaco", true, "MC5811222000010123456789030",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Principauté de Monaco", null, "7, rue du Gabian",
           "MC98000", "amaf@amaf.mc", null)
    ),

    /**
     * <strong>Moldova ({@code MD})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 2!c18!c}<br>
     * Example: {@code MD24AG000225100013104168}
     */
    MD(StructureData.builder().withIbanLength(24)
         .withBbanPattern("2!c18!c")
         .withBankCode("2!c", IndexRange.of(4, 6))
         .withAccountNumber(IndexRange.of(6, 24))
         .build(),
       MetaData.of(
           "Moldova", false, "MD24AG000225100013104168",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "National Bank of Moldova", "Payments System", "1 Grigore Vieru Avenue",
           "MD-2005 Chisinau", null, null)
    ),

    /**
     * <strong>Montenegro ({@code ME})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n13!n2!n}<br>
     * Example: {@code ME25505000012345678951}
     */
    ME(StructureData.builder().withIbanLength(22)
         .withBbanPattern("3!n13!n2!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 20))
         .build(),
       MetaData.of(
           "Montenegro", false, "ME25505000012345678951",
           YearMonth.of(2010, 5)),
       ContactData.of(
           "Association of Montenegrin Banks", null, "Novaka Miloseva bb",
           "81000 Podgorica", "udruzenjebanaka@t-com.me", "+ 381 81232028")
    ),

    /**
     * <strong>North Macedonia ({@code MK})</strong><p>
     * IBAN Length: 19<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n10!c2!n}<br>
     * Example: {@code MK07250120000058984}
     */
    MK(StructureData.builder().withIbanLength(19)
         .withBbanPattern("3!n10!c2!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 17))
         .build(),
       MetaData.of(
           "North Macedonia", false, "MK07250120000058984",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "National Bank of the Republic of Macedonia", null, "K.J.Pitu 1",
           "1000 Skopje", null, null)
    ),

    /**
     * <strong>Mongolia ({@code MN})</strong><p>
     * IBAN Length: 20<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n12!n}<br>
     * Example: {@code MN121234123456789123}
     */
    MN(StructureData.builder().withIbanLength(20)
         .withBbanPattern("4!n12!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 20))
         .build(),
       MetaData.of(
           "Mongolia", false, "MN121234123456789123",
           YearMonth.of(2023, 4)),
       ContactData.of(
           "Bank of Mongolia (The Central Bank)", null, "Baga toiruu-3",
           "15160 Ulaanbaatar", null, "976-11-327510")
    ),

    /**
     * <strong>Mauritania ({@code MR})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 5!n5!n11!n2!n}<br>
     * Example: {@code MR1300020001010000123456753}
     */
    MR(StructureData.builder().withIbanLength(27)
         .withBbanPattern("5!n5!n11!n2!n")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withBranchCode("5!n", IndexRange.of(9, 14))
         .withAccountNumber(IndexRange.of(14, 25))
         .build(),
       MetaData.of(
           "Mauritania", false, "MR1300020001010000123456753",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Banque Centrale de Mauritanie", null, "Avenue de l'Indépendance",
           "BP 623 Nouakchott", "info@bcm.mr", "+ 222 45255206")
    ),

    /**
     * <strong>Malta ({@code MT})</strong><p>
     * IBAN Length: 31<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a5!n18!c}<br>
     * Example: {@code MT84MALT011000012345MTLCAST001S}
     */
    MT(StructureData.builder().withIbanLength(31)
         .withBbanPattern("4!a5!n18!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withBranchCode("5!n", IndexRange.of(8, 13))
         .withAccountNumber(IndexRange.of(13, 31))
         .build(),
       MetaData.of(
           "Malta", true, "MT84MALT011000012345MTLCAST001S",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Malta Bankers' Association", "The Secretary General", "48/2 Birkirkara Road",
           "Attard ATD1210", "info@maltabankers.org", "+ 356 21412210 / + 356 21410572")
    ),

    /**
     * <strong>Mauritius ({@code MU})</strong><p>
     * IBAN Length: 30<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a2!n2!n12!n3!n3!a}<br>
     * Example: {@code MU17BOMM0101101030300200000MUR}
     */
    MU(StructureData.builder().withIbanLength(30)
         .withBbanPattern("4!a2!n2!n12!n3!n3!a")
         .withBankCode("4!a2!n", IndexRange.of(4, 10))
         .withBranchCode("2!n", IndexRange.of(10, 12))
         .withAccountNumber(IndexRange.of(12, 30))
         .build(),
       MetaData.of(
           "Mauritius", false, "MU17BOMM0101101030300200000MUR",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "The Central Bank of Mauritius", null, "Sir William Newton Street",
           "Port Louis", null, null)
    ),

    /**
     * <strong>Mozambique ({@code MZ})</strong><p>
     * IBAN Length: 25<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n4!n11!n2!n}<br>
     * Example: {@code MZ59000800005138555713187}
     */
    MZ(StructureData.builder().withIbanLength(25)
         .withBbanPattern("4!n4!n11!n2!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 23))
         .build(),
       MetaData.of(
           "Mozambique", false, "MZ59000800005138555713187",
           null),
       null),

    /**
     * <strong>Nicaragua ({@code NI})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a20!n}<br>
     * Example: {@code NI45BAPR00000013000003558124}
     */
    NI(StructureData.builder().withIbanLength(28)
         .withBbanPattern("4!a20!n")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 28))
         .build(),
       MetaData.of(
           "Nicaragua", false, "NI45BAPR00000013000003558124",
           YearMonth.of(2024, 12)),
       ContactData.of(
           "Banco Central de Nicaragua", null, "Paso a Desnivel Nejapa, 100 metros al este, Pista Juan Pablo II",
           "2252 - 2253 Managua", null, null)
    ),

    /**
     * <strong>Netherlands ({@code NL})</strong><p>
     * IBAN Length: 18<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a10!n}<br>
     * Example: {@code NL91ABNA0417164300}
     */
    NL(StructureData.builder().withIbanLength(18)
         .withBbanPattern("4!a10!n")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 18))
         .build(),
       MetaData.of(
           "Netherlands", true, "NL91ABNA0417164300",
           YearMonth.of(2020, 9)),
       ContactData.of(
           "Betaalvereniging Nederland", null, "P.O Box 83073",
           "1080 AB Amsterdam", "sepa@betaalvereniging.nl", "+ 31 203051900")
    ),

    /**
     * <strong>Norway ({@code NO})</strong><p>
     * IBAN Length: 15<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!n6!n1!n}<br>
     * Example: {@code NO9386011117947}
     */
    NO(StructureData.builder().withIbanLength(15)
         .withBbanPattern("4!n6!n1!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 14))
         .build(),
       MetaData.of(
           "Norway", true, "NO9386011117947",
           YearMonth.of(2009, 8)),
       ContactData.of(
           "DnB NOR Bank", null, "p.o.box 7100",
           "5020 Bergen", null, null)
    ),

    /**
     * <strong>Oman ({@code OM})</strong><p>
     * IBAN Length: 23<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n16!c}<br>
     * Example: {@code OM810180000001299123456}
     */
    OM(StructureData.builder().withIbanLength(23)
         .withBbanPattern("3!n16!c")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 23))
         .build(),
       MetaData.of(
           "Oman", false, "OM810180000001299123456",
           YearMonth.of(2024, 3)),
       ContactData.of(
           "Central Bank of Oman", null, "Head Office, Al Markazi, Building Number:44 P.O. Box 1161",
           "112 Ruwi - Commercial Business District - Muscat", "cso@cbo.gov.om", null)
    ),

    /**
     * <strong>Pakistan ({@code PK})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a16!c}<br>
     * Example: {@code PK36SCBL0000001123456702}
     */
    PK(StructureData.builder().withIbanLength(24)
         .withBbanPattern("4!a16!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 24))
         .build(),
       MetaData.of(
           "Pakistan", false, "PK36SCBL0000001123456702",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "State Bank of Pakistan", "Payment Systems", "4th Floor, Main Building, I.I. Chundrigar Road.",
           "74000 Karachi – Sindh – Pakistan", null, null)
    ),

    /**
     * <strong>Poland ({@code PL})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 8!n16!n}<br>
     * Example: {@code PL61109010140000071219812874}
     */
    PL(StructureData.builder().withIbanLength(28)
         .withBbanPattern("8!n16!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withBranchCode("4!n", IndexRange.of(7, 11))
         .withAccountNumber(IndexRange.of(12, 28))
         .build(),
       MetaData.of(
           "Poland", true, "PL61109010140000071219812874",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Narodowy Bank Polski", "Payment Systems Deparment", "Świętokrzyska 11/21",
           "00 – 919 Warsaw", "sekretariat.dsp@nbp.pl", "48 22 185 27 25")
    ),

    /**
     * <strong>Palestine ({@code PS})</strong><p>
     * IBAN Length: 29<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a21!c}<br>
     * Example: {@code PS92PALS000000000400123456702}
     */
    PS(StructureData.builder().withIbanLength(29)
         .withBbanPattern("4!a21!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 29))
         .build(),
       MetaData.of(
           "Palestine", false, "PS92PALS000000000400123456702",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Palestine Monetary Authority", "Payment Systems", "Al-Ramouni Nablus Street",
           "452 AL-BIREH", "psdsupport@pma.ps", null)
    ),

    /**
     * <strong>Portugal ({@code PT})</strong><p>
     * IBAN Length: 25<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!n4!n11!n2!n}<br>
     * Example: {@code PT50000201231234567890154}
     */
    PT(StructureData.builder().withIbanLength(25)
         .withBbanPattern("4!n4!n11!n2!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 23))
         .build(),
       MetaData.of(
           "Portugal", true, "PT50000201231234567890154",
           YearMonth.of(2025, 6)),
       ContactData.of(
           "Banco de Portugal", "Payment Systems Department", "Rua do Comércio 148",
           "1100-150 Lisboa", "dpg@bportugal.pt", "+ 351 217813000")
    ),

    /**
     * <strong>Qatar ({@code QA})</strong><p>
     * IBAN Length: 29<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a21!c}<br>
     * Example: {@code QA58DOHB00001234567890ABCDEFG}
     */
    QA(StructureData.builder().withIbanLength(29)
         .withBbanPattern("4!a21!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 29))
         .build(),
       MetaData.of(
           "Qatar", false, "QA58DOHB00001234567890ABCDEFG",
           YearMonth.of(2014, 1)),
       ContactData.of(
           "Qatar Central Bank", "Banking Payments and Settlement System", "Abdulla Bin Jassim Street",
           "1234 Doha", null, null)
    ),

    /**
     * <strong>Romania ({@code RO})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!a16!c}<br>
     * Example: {@code RO49AAAA1B31007593840000}
     */
    RO(StructureData.builder().withIbanLength(24)
         .withBbanPattern("4!a16!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 24))
         .build(),
       MetaData.of(
           "Romania", true, "RO49AAAA1B31007593840000",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "National Bank of Romania", null, "Lipscani St.,25th",
           "Sector 3, Bucharest 030031", null, null)
    ),

    /**
     * <strong>Serbia ({@code RS})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n13!n2!n}<br>
     * Example: {@code RS35260005601001611379}
     */
    RS(StructureData.builder().withIbanLength(22)
         .withBbanPattern("3!n13!n2!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 20))
         .build(),
       MetaData.of(
           "Serbia", false, "RS35260005601001611379",
           YearMonth.of(2017, 3)),
       ContactData.of(
           "National bank of Serbia", null, "Nemanjina 17",
           "11000 Belgrade", "platni.sistem@nbs.rs", null)
    ),

    /**
     * <strong>Russia ({@code RU})</strong><p>
     * IBAN Length: 33<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 9!n5!n15!c}<br>
     * Example: {@code RU0304452522540817810538091310419}
     */
    RU(StructureData.builder().withIbanLength(33)
         .withBbanPattern("9!n5!n15!c")
         .withBankCode("9!n", IndexRange.of(4, 13))
         .withBranchCode("5!n", IndexRange.of(13, 18))
         .withAccountNumber(IndexRange.of(18, 33))
         .build(),
       MetaData.of(
           "Russia", false, "RU0304452522540817810538091310419",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "The Central Bank of the Russian Federation", null, "Neglinnaya Street, 12",
           "Moscow", "svc_dnps_ornps@cbr.ru", null)
    ),

    /**
     * <strong>Saudi Arabia ({@code SA})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 2!n18!c}<br>
     * Example: {@code SA0380000000608010167519}
     */
    SA(StructureData.builder().withIbanLength(24)
         .withBbanPattern("2!n18!c")
         .withBankCode("2!n", IndexRange.of(4, 6))
         .withAccountNumber(IndexRange.of(6, 24))
         .build(),
       MetaData.of(
           "Saudi Arabia", false, "SA0380000000608010167519",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "SAMA, Head Office", "General Department of Payment Systems", "P.O. BOX 2992",
           "Riyadh 11169", "gdps@sama.gov.sa", "+ 966 114662015")
    ),

    /**
     * <strong>Seychelles ({@code SC})</strong><p>
     * IBAN Length: 31<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a2!n2!n16!n3!a}<br>
     * Example: {@code SC18SSCB11010000000000001497USD}
     */
    SC(StructureData.builder().withIbanLength(31)
         .withBbanPattern("4!a2!n2!n16!n3!a")
         .withBankCode("4!a2!n", IndexRange.of(4, 10))
         .withBranchCode("2!n", IndexRange.of(10, 12))
         .withAccountNumber(IndexRange.of(12, 28))
         .build(),
       MetaData.of(
           "Seychelles", false, "SC18SSCB11010000000000001497USD",
           YearMonth.of(2019, 10)),
       ContactData.of(
           "Central Bank of Seychelles", null, "Independence Avenue",
           "Victoria - Mahe", "Psd@cbs.sc; BankingServices@cbs.sc", null)
    ),

    /**
     * <strong>Sudan ({@code SD})</strong><p>
     * IBAN Length: 18<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 2!n12!n}<br>
     * Example: {@code SD2129010501234001}
     */
    SD(StructureData.builder().withIbanLength(18)
         .withBbanPattern("2!n12!n")
         .withBankCode("2!n", IndexRange.of(4, 6))
         .withAccountNumber(IndexRange.of(6, 18))
         .build(),
       MetaData.of(
           "Sudan", false, "SD2129010501234001",
           YearMonth.of(2021, 10)),
       ContactData.of(
           "Central Bank of Sudan (CBOS)", null, "HQ Building of Central Bank of SudanAljammah St.",
           "Khartoum 11111/313", null, null)
    ),

    /**
     * <strong>Sweden ({@code SE})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n16!n1!n}<br>
     * Example: {@code SE4550000000058398257466}
     */
    SE(StructureData.builder().withIbanLength(24)
         .withBbanPattern("3!n16!n1!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 24))
         .build(),
       MetaData.of(
           "Sweden", true, "SE4550000000058398257466",
           YearMonth.of(2009, 8)),
       ContactData.of(
           "Swedish Bankers' Association", null, null,
           "SE - 103 94 Stockholm", null, null)
    ),

    /**
     * <strong>Slovenia ({@code SI})</strong><p>
     * IBAN Length: 19<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 2!n3!n8!n2!n}<br>
     * Example: {@code SI56263300012039086}
     */
    SI(StructureData.builder().withIbanLength(19)
         .withBbanPattern("2!n3!n8!n2!n")
         .withBankCode("5!n", IndexRange.of(4, 6))
         .withBranchCode("3!n", IndexRange.of(6, 9))
         .withAccountNumber(IndexRange.of(9, 17))
         .build(),
       MetaData.of(
           "Slovenia", true, "SI56263300012039086",
           YearMonth.of(2016, 10)),
       ContactData.of(
           "Bank of Slovenia", "Payment and Settlement Systems", "Slovenska 35",
           "SI-1505 Ljubljana", "Pomoc.PS@bsi.si", "+389 1 4719 568")
    ),

    /**
     * <strong>Slovakia ({@code SK})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 4!n6!n10!n}<br>
     * Example: {@code SK3112000000198742637541}
     */
    SK(StructureData.builder().withIbanLength(24)
         .withBbanPattern("4!n6!n10!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 24))
         .build(),
       MetaData.of(
           "Slovakia", true, "SK3112000000198742637541",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "National Bank of Slovakia", null, "Imricha Karvaša 1",
           "813 25 Bratislava 1", "info@nbs.sk", null)
    ),

    /**
     * <strong>San Marino ({@code SM})</strong><p>
     * IBAN Length: 27<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 1!a5!n5!n12!c}<br>
     * Example: {@code SM86U0322509800000000270100}
     */
    SM(StructureData.builder().withIbanLength(27)
         .withBbanPattern("1!a5!n5!n12!c")
         .withBankCode("5!n", IndexRange.of(5, 10))
         .withBranchCode("5!n", IndexRange.of(10, 15))
         .withAccountNumber(IndexRange.of(15, 27))
         .build(),
       MetaData.of(
           "San Marino", true, "SM86U0322509800000000270100",
           YearMonth.of(2016, 8)),
       ContactData.of(
           "Banca Centrale della Repubblica di San Marino", "Payments System", "Via del Voltone, 120",
           "San Marino 47890", "sistemi.pagamento@bcsm.sm", "+ 378 882325")
    ),

    /**
     * <strong>Somalia ({@code SO})</strong><p>
     * IBAN Length: 23<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n3!n12!n}<br>
     * Example: {@code SO211000001001000100141}
     */
    SO(StructureData.builder().withIbanLength(23)
         .withBbanPattern("4!n3!n12!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("3!n", IndexRange.of(8, 11))
         .withAccountNumber(IndexRange.of(11, 23))
         .build(),
       MetaData.of(
           "Somalia", false, "SO211000001001000100141",
           YearMonth.of(2025, 2)),
       ContactData.of(
           "Central Bank of Somalia", null, "Corso Somalia, 55 P.O Box 11",
           "Mogadishu", "info@centralbank.gov.so", null)
    ),

    /**
     * <strong>Sao Tome and Principe ({@code ST})</strong><p>
     * IBAN Length: 25<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n4!n11!n2!n}<br>
     * Example: {@code ST23000100010051845310146}
     */
    ST(StructureData.builder().withIbanLength(25)
         .withBbanPattern("4!n4!n11!n2!n")
         .withBankCode("4!n", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 25))
         .build(),
       MetaData.of(
           "Sao Tome and Principe", false, "ST23000100010051845310146",
           YearMonth.of(2020, 5)),
       ContactData.of(
           "Banco Central de Sao Tome e Principe", "DSP", "Avenida Marginal 12 de Julho",
           "CP 13 Sao Tome", "dsp@bcstp.st", "+239 2243700")
    ),

    /**
     * <strong>El Salvador ({@code SV})</strong><p>
     * IBAN Length: 28<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a20!n}<br>
     * Example: {@code SV62CENR00000000000000700025}
     */
    SV(StructureData.builder().withIbanLength(28)
         .withBbanPattern("4!a20!n")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 28))
         .build(),
       MetaData.of(
           "El Salvador", false, "SV62CENR00000000000000700025",
           YearMonth.of(2021, 3)),
       ContactData.of(
           "Banco Central de Reserva de El Salvador", "Departamento de Pagos y Valores", "1a Calle Poniente y 7Av. Nte. N 418",
           "San Salvador", "maria.delgado@bcr.gov.sv", "503 2281 8831")
    ),

    /**
     * <strong>Timor-Leste ({@code TL})</strong><p>
     * IBAN Length: 23<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 3!n14!n2!n}<br>
     * Example: {@code TL380080012345678910157}
     */
    TL(StructureData.builder().withIbanLength(23)
         .withBbanPattern("3!n14!n2!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 21))
         .build(),
       MetaData.of(
           "Timor-Leste", false, "TL380080012345678910157",
           YearMonth.of(2014, 11)),
       ContactData.of(
           "Banco Central de Timor-Leste", null, "Avenida Bispo Medeiros",
           "Dili", null, null)
    ),

    /**
     * <strong>Tunisia ({@code TN})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 2!n3!n13!n2!n}<br>
     * Example: {@code TN5910006035183598478831}
     */
    TN(StructureData.builder().withIbanLength(24)
         .withBbanPattern("2!n3!n13!n2!n")
         .withBankCode("2!n", IndexRange.of(4, 6))
         .withBranchCode("3!n", IndexRange.of(6, 9))
         .withAccountNumber(IndexRange.of(9, 22))
         .build(),
       MetaData.of(
           "Tunisia", false, "TN5910006035183598478831",
           YearMonth.of(2016, 5)),
       ContactData.of(
           "Tunisia's Professional Association for Banks & Financial Institutions", null, null,
           null, "info@apbt.org.tn", "+ 216 71904423")
    ),

    /**
     * <strong>Turkey ({@code TR})</strong><p>
     * IBAN Length: 26<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 5!n1!n16!c}<br>
     * Example: {@code TR330006100519786457841326}
     */
    TR(StructureData.builder().withIbanLength(26)
         .withBbanPattern("5!n1!n16!c")
         .withBankCode("5!n", IndexRange.of(4, 9))
         .withAccountNumber(IndexRange.of(10, 26))
         .build(),
       MetaData.of(
           "Turkey", false, "TR330006100519786457841326",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Central Bank of the Republic of Turkey", "Payment Systems", "Anafartalar Mahallesi İstiklal Cad. No:10 Ulus Altındağ",
           "Ankara / 06050", "paymentsystems@tcmb.gov.tr", "+ 90 3125077901 / 02")
    ),

    /**
     * <strong>Ukraine ({@code UA})</strong><p>
     * IBAN Length: 29<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 6!n19!c}<br>
     * Example: {@code UA213223130000026007233566001}
     */
    UA(StructureData.builder().withIbanLength(29)
         .withBbanPattern("6!n19!c")
         .withBankCode("6!n", IndexRange.of(4, 10))
         .withAccountNumber(IndexRange.of(10, 29))
         .build(),
       MetaData.of(
           "Ukraine", false, "UA213223130000026007233566001",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Association UkrSWIFT", "Executive Board", "21A, Observatoma Str.",
           "04053 Kiev", "ukrswift@ukrswift.org", null)
    ),

    /**
     * <strong>Vatican City State ({@code VA})</strong><p>
     * IBAN Length: 22<br>
     * SEPA: Yes<br>
     * BBAN Structure: {@code 3!n15!n}<br>
     * Example: {@code VA59001123000012345678}
     */
    VA(StructureData.builder().withIbanLength(22)
         .withBbanPattern("3!n15!n")
         .withBankCode("3!n", IndexRange.of(4, 7))
         .withAccountNumber(IndexRange.of(7, 22))
         .build(),
       MetaData.of(
           "Vatican City State", true, "VA59001123000012345678",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "Financial Information Authority (Autorita di Informazione Finanziaria - AIF)", "Office for Supervision and Regulation", "Palazzo San Carlo",
           " 00120", "uvr@aif.va", "+39 06 69871522")
    ),

    /**
     * <strong>Virgin Islands ({@code VG})</strong><p>
     * IBAN Length: 24<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a16!n}<br>
     * Example: {@code VG96VPVG0000012345678901}
     */
    VG(StructureData.builder().withIbanLength(24)
         .withBbanPattern("4!a16!n")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withAccountNumber(IndexRange.of(8, 24))
         .build(),
       MetaData.of(
           "Virgin Islands", false, "VG96VPVG0000012345678901",
           YearMonth.of(2025, 10)),
       ContactData.of(
           "VP Bank House", null, "156 Mainstreet",
           "VG1110 Road Town Tortola", null, null)
    ),

    /**
     * <strong>Kosovo ({@code XK})</strong><p>
     * IBAN Length: 20<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!n10!n2!n}<br>
     * Example: {@code XK051212012345678906}
     */
    XK(StructureData.builder().withIbanLength(20)
         .withBbanPattern("4!n10!n2!n")
         .withBankCode("2!n", IndexRange.of(4, 6))
         .withBranchCode("2!n", IndexRange.of(6, 8))
         .withAccountNumber(IndexRange.of(8, 18))
         .build(),
       MetaData.of(
           "Kosovo", false, "XK051212012345678906",
           YearMonth.of(2016, 9)),
       ContactData.of(
           "Central Bank of the Republic of Kosovo", "Payment Systems", "Garibaldi 33",
           "Prishtina / 10000", "payment.systems@bqk-kos.org", "+ 381 (0)38222055 (ext. 209, 210 and 211)")
    ),

    /**
     * <strong>Yemen ({@code YE})</strong><p>
     * IBAN Length: 30<br>
     * SEPA: No<br>
     * BBAN Structure: {@code 4!a4!n18!c}<br>
     * Example: {@code YE15CBYE0001018861234567891234}
     */
    YE(StructureData.builder().withIbanLength(30)
         .withBbanPattern("4!a4!n18!c")
         .withBankCode("4!a", IndexRange.of(4, 8))
         .withBranchCode("4!n", IndexRange.of(8, 12))
         .withAccountNumber(IndexRange.of(12, 30))
         .build(),
       MetaData.of(
           "Yemen", false, "YE15CBYE0001018861234567891234",
           YearMonth.of(2024, 7)),
       ContactData.of(
           "Central Bank of Yemen", "Payment Systems Depatment", "Crater Aledaroos Street 452",
           "Aden", null, null)
    );

    private final StructureData                    structureData;
    private final MetaData                         metaData;
    private final ContactData                      contactData;

    private final String                           countryFlag;
    private final Pattern                          ibanRegex;
    private final CountryValidator                 countryValidator;
    private IbanRegistry                           primary;

    /** The minimum required length: Country Code (2) + Check Digits (2). */
    static final int                               MIN_IBAN_BASE_LENGTH = 4;

    /** ISO 13616 standard minimum. */
    static final int                               MIN_IBAN_LENGTH      = Arrays.stream(values())
        .mapToInt(IbanRegistry::getIbanLength).min().orElse(MIN_IBAN_BASE_LENGTH);

    /** ISO 13616 standard maximum. */
    static final int                               MAX_IBAN_LENGTH      = Arrays.stream(values())
        .mapToInt(IbanRegistry::getIbanLength).max().orElse(34);

    /** Begin index of IBAN check digits within the full IBAN string (position 3, 0-based index 2). */
    static final int                               INDEX_CHECK_DIGITS   = 2;

    /** Begin index of BBAN within IBAN (position 5, 0-based index 4). */
    static final int                               INDEX_BBAN           = MIN_IBAN_BASE_LENGTH;

    /** Maximum length of BBAN. */
    static final int                               MAX_BBAN_LENGTH      = MAX_IBAN_LENGTH - INDEX_BBAN;

    /** The map for quick lookups by country code. */
    private static final Map<CharSequence, IbanRegistry> CODE_MAP             = buildCodeMap();

    /**
     * Main constructor for {@code IbanRegistry} enum constants.
     * <p>
     * Initializes the country's IBAN structure, format details, and regulatory contact information.
     *
     * @param structureData The IBAN structure details object.
     * @param metaData The metadata object.
     * @param contactData The contact details object.
     */
    IbanRegistry(
        StructureData structureData,
        MetaData metaData,
        ContactData contactData
        ) {

        this.structureData = Objects.requireNonNull(structureData, "structureData required");
        this.metaData = Objects.requireNonNull(metaData, "metaData required");
        this.contactData = Optional.ofNullable(contactData).orElseGet(ContactData::new);

        this.countryFlag = CountryUtil.createFlagEmoji(name());

        String fullIbanPattern = "2!a2!n" + structureData.bbanPatternStr();
        this.ibanRegex = Pattern.compile('^' + IbanPatternConverter.convertToRegex(fullIbanPattern) + '$');

        this.countryValidator = loadValidator(this.name());
    }

    /**
     * Secondary constructor for country codes that share their registry data with a primary country.
     * <p>
     * Copies all structural and contact data from the specified primary entry.
     *
     * @param countryName The full English name of the country.
     * @param primary     The {@code IbanRegistry} enum constant whose data is to be used.
     */
    IbanRegistry(String countryName, IbanRegistry primary) {
        // Delegiert an den Hauptkonstruktor mit den Objekten des Primary-Eintrags
        this(
            primary.structureData,
            MetaData.of(
                countryName,
                primary.isSepa(),
                primary.getIbanExample(),
                primary.getLastUpdate()
            ),
            primary.contactData
        );
        this.primary = primary;
    }

    /**
     * Returns the ISO 3166-1 Alpha-2 country code (e.g., "DE", "IT").
     *
     * @return The two-letter country code.
     */
    String getCountryCode() {
        return name();
    }

    /**
     * Returns the full English name of the country.
     *
     * @return The country name.
     */
    String getCountryName() {
        return metaData.getCountryName();
    }

    /**
     * Returns the two-character country flag emoji.
     *
     * @return The country flag emoji string.
     */
    String getCountryFlag() {
        return countryFlag;
    }

    /**
     * Returns whether the country is a part of the SEPA zone.
     *
     * @return {@code true} if the country is in SEPA, {@code false} otherwise.
     */
    boolean isSepa() {
        return metaData.isSepa();
    }

    /**
     * Returns the fixed length of the IBAN for this country.
     *
     * @return The total IBAN length.
     */
    int getIbanLength() {
        return structureData.ibanLength();
    }

    /**
     * Returns the regular expression {@code Pattern} object of the IBAN.
     *
     * @return The IBAN pattern object.
     */
    Pattern getIbanRegex() {
        return ibanRegex;
    }

    /**
     * Returns the length of the BBAN (Basic Bank Account Number) part of the IBAN.
     *
     * @return The BBAN length.
     */
    int getBbanLength() {
        return structureData.getBbanLength();
    }

    /**
     * Returns the BBAN structure pattern string (e.g., "4!n4!n12!c").
     *
     * @return The BBAN pattern string.
     */
    String getBbanPatternStr() {
        return structureData.bbanPatternStr();
    }

    /**
     * Returns an example of a valid IBAN for this country.
     *
     * @return The IBAN example string.
     */
    String getIbanExample() {
        return metaData.getIbanExample();
    }

    /**
     * Returns the character pattern string for the Bank Identifier Code.
     *
     * @return The bank code pattern string.
     */
    String getBankCodePatternStr() {
        return structureData.bankCodePatternStr();
    }

    /**
     * Returns the index range defining the position of the Bank Code within the IBAN.
     *
     * @return The {@code IndexRange} for the bank code.
     */
    IndexRange getBankCodeIndexRange() {
        return structureData.bankCodeIndexRange();
    }

    /**
     * Returns the character pattern string for the Branch Identifier Code.
     *
     * @return The branch code pattern string.
     */
    String getBranchCodePattern() {
        return structureData.branchCodePatternStr();
    }

    /**
     * Returns the index range defining the position of the Branch Code within the IBAN.
     *
     * @return The {@code IndexRange} for the branch code, or {@code null}.
     */
    IndexRange getBranchCodeIndexRange() {
        return structureData.branchCodeIndexRange();
    }

    /**
     * Returns whether the country's BBAN structure defines a separate Branch Code part.
     *
     * @return {@code true} if a branch code exists, {@code false} otherwise.
     */
    boolean hasBranchCode() {
        return structureData.hasBranchCode();
    }

    /**
     * Returns the index range defining the position of the Account Number within the IBAN.
     *
     * @return The {@code IndexRange} for the account number.
     */
    IndexRange getAccountNumberIndexRange() {
        return structureData.accountNumberIndexRange();
    }

    /**
     * Returns the name of the regulatory or financial organization responsible for the IBAN registry.
     *
     * @return The organization's name.
     */
    String getOrganisation() {
        return contactData.getOrganisation();
    }

    /**
     * Returns the relevant department name of the organization.
     *
     * @return The department name.
     */
    String getDepartment() {
        return contactData.getDepartment();
    }

    /**
     * Returns the street address of the organization.
     *
     * @return The street address.
     */
    String getStreetAddress() {
        return contactData.getStreetAddress();
    }

    /**
     * Returns the city and postal code of the organization.
     *
     * @return The city and postcode.
     */
    String getCityPostcode() {
        return contactData.getCityPostcode();
    }

    /**
     * Returns the generic contact email address for the department.
     *
     * @return The email address.
     */
    String getDepartmentGenericEmail() {
        return contactData.getDepartmentGenericEmail();
    }

    /**
     * Returns the contact telephone number for the department.
     *
     * @return The telephone number.
     */
    String getDepartmentTel() {
        return contactData.getDepartmentTel();
    }

    /**
     * Returns the month and year the registry data was last updated by the source.
     *
     * @return The {@code YearMonth} of the last update.
     */
    YearMonth getLastUpdate() {
        return metaData.getLastUpdate();
    }

    /**
     * Returns the optional {@link CountryValidator} instance used for country-specific structure validation.
     *
     * @return The country validator implementation, or {@code null} if one is not found.
     */
    CountryValidator getCountryValidator() {
        return countryValidator;
    }

    /**
     * Returns the primary {@code IbanRegistry} entry if this entry is a secondary code
     * that shares data with another country (e.g., {@code AX} points to {@code FI}).
     *
     * @return The primary {@code IbanRegistry} entry, or {@code null} if this is a primary entry.
     */
    IbanRegistry getPrimary() {
        return primary;
    }

    /**
     * Provides a detailed representation of the registry entry's structure.
     *
     * @return A string representation of this registry entry.
     */
    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", getClass().getSimpleName() + "[", "]")
            .add(getCountryCode() + " (" + getCountryName() + ")")
            .add("SEPA country: " + (isSepa() ? "Yes" : "No"))
            .add("IBAN len: " + getIbanLength())
            .add("BBAN pattern: " + getBbanPatternStr())
            .add("Bank Code: " + Objects.toString(getBankCodeIndexRange()));
        if (getBranchCodeIndexRange() != null) {
            joiner.add("Branch Code: " + Objects.toString(getBranchCodeIndexRange()));
        }
        return joiner
            .add("Account No: " + Objects.toString(getAccountNumberIndexRange()))
            .add("IBAN Example: " + getIbanExample())
            .add("Organization: " + getOrganisation())
            .add("Last Update: " + getLastUpdate())
            .toString();
    }

    /**
     * Dynamically loads and instantiates the country-specific IBAN validator
     * using reflection based on the two-letter country code.
     * <p>
     * This method expects the validator implementation to be defined as a public
     * nested static class within the {@code ICountryValidator} interface,
     * named after the country code (e.g., {@code ICountryValidator.AD} for "AD").
     *
     * @param countryCode The two-letter country code (e.g., "DE", "AD").
     * @return            The instantiated {@link CountryValidator} for the given country,
     * or {@code null} if the validator class cannot be found or instantiated.
     */
    private static CountryValidator loadValidator(final String countryCode) {
        String className = CountryValidator.class.getName() + '$' + countryCode;

        try {
            // Reflektiver Aufruf des Konstruktors der inneren statischen Klasse
            Class<?> validatorClass = Class.forName(className);
            Object instance = validatorClass.getDeclaredConstructor().newInstance();
            return (CountryValidator) instance;

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
            return null;
        }
    }

    /**
     * Builds the static, immutable map for quick {@code IbanRegistry} lookups by country code.
     *
     * @return An unmodifiable {@code Map<CharSequence, IbanRegistry>} ready for static member assignment.
     * The map keys are interned country codes.
     */
    private static Map<CharSequence, IbanRegistry> buildCodeMap() {
        Map<String, IbanRegistry> map = new LinkedHashMap<>();
        for (IbanRegistry registry : values()) {
            map.put(registry.name().intern(), registry);
        }
        return Collections.unmodifiableMap(map);
    }

    /**
     * Returns the registry entry for a given country code instantly.
     *
     * @param code The two-letter country code (e.g., "DE").
     * @return     The {@code IbanRegistry} entry, or {@code null} if the country code is unsupported.
     */
    public static IbanRegistry getByCode(final CharSequence code) {
        return CODE_MAP.get(code);
    }

    /**
     * Returns the registry entry for a given country code instantly.
     *
     * @param c0 The first character of the country code.
     * @param c1 The second character of the country code.
     * @return   The {@code IbanRegistry} entry, or {@code null} if the country code is unsupported.
     */
    public static IbanRegistry getByCode(final char c0, final char c1) {
        return getByCode(new String(new char[] {c0, c1}).intern());
    }

    /**
     * The immutable class defining the structure of the BBAN and its component index ranges.
     * The Builder Pattern is used to handle optional index ranges and improve legibility.
     */
    private static final class StructureData {
        private final int        ibanLength;
        private final String     bbanPatternStr;
        private final String     bankCodePatternStr;
        private final IndexRange bankCodeIndexRange;
        private final String     branchCodePatternStr;
        private final IndexRange branchCodeIndexRange;
        private final IndexRange accountNumberIndexRange;

        // Privater Konstruktor akzeptiert den Builder
        private StructureData(Builder builder) {
            if (builder.ibanLength <= 0) {
                throw new IllegalStateException("IBAN length must be set and positive.");
            }
            this.ibanLength = builder.ibanLength;
            this.bbanPatternStr = Objects.requireNonNull(builder.bbanPatternStr, "bbanPatternStr required");
            this.bankCodePatternStr = builder.bankCodePatternStr;
            this.bankCodeIndexRange = builder.bankCodeIndexRange;
            this.branchCodePatternStr = builder.branchCodePatternStr;
            this.branchCodeIndexRange = builder.branchCodeIndexRange;
            this.accountNumberIndexRange = Objects.requireNonNull(builder.accountNumberIndexRange, "accountNumberIndexRange required");
        }

        public static Builder builder() {
            return new Builder();
        }

        // --- Builder Innere Klasse ---

        public static final class Builder {
            // Alle Felder sind optional initialisiert (0 oder null)
            private int ibanLength;
            private String bbanPatternStr;
            private IndexRange accountNumberIndexRange;

            // Optionale Felder (Defaulted to null)
            private String bankCodePatternStr;
            private IndexRange bankCodeIndexRange;
            private String branchCodePatternStr;
            private IndexRange branchCodeIndexRange;

            private Builder() {
                // Parameterloser Konstruktor
            }

            // NEU: Setter für die obligatorischen Felder
            public Builder withIbanLength(int ibanLength) {
                this.ibanLength = ibanLength;
                return this;
            }

            public Builder withBbanPattern(String bbanPatternStr) {
                this.bbanPatternStr = bbanPatternStr;
                return this;
            }

            public Builder withAccountNumber(IndexRange accountNumberIndexRange) {
                this.accountNumberIndexRange = accountNumberIndexRange;
                return this;
            }

            public Builder withBankCode(String bankCodePatternStr, IndexRange bankCodeIndexRange) {
                this.bankCodePatternStr = bankCodePatternStr;
                this.bankCodeIndexRange = bankCodeIndexRange;
                return this;
            }

            public Builder withBranchCode(String branchCodePatternStr, IndexRange branchCodeIndexRange) {
                this.branchCodePatternStr = branchCodePatternStr;
                this.branchCodeIndexRange = branchCodeIndexRange;
                return this;
            }

            public StructureData build() {
                // Führen Sie die Validierung der Pflichtfelder durch
                if (ibanLength <= 0) {
                    throw new IllegalStateException("IBAN length must be set and positive.");
                }
                Objects.requireNonNull(bbanPatternStr, "BBAN pattern must be set.");
                Objects.requireNonNull(accountNumberIndexRange, "Account number index range must be set.");

                return new StructureData(this);
            }
        }

        public int ibanLength() {
            return ibanLength;
        }

        public String bbanPatternStr() {
            return bbanPatternStr;
        }

        public String bankCodePatternStr() {
            return bankCodePatternStr;
        }

        public IndexRange bankCodeIndexRange() {
            return bankCodeIndexRange;
        }

        public String branchCodePatternStr() {
            return branchCodePatternStr;
        }

        public IndexRange branchCodeIndexRange() {
            return branchCodeIndexRange;
        }

        public IndexRange accountNumberIndexRange() {
            return accountNumberIndexRange;
        }

        public boolean hasBranchCode() {
            return branchCodeIndexRange != null;
        }

        public int getBbanLength() {
            return ibanLength - INDEX_BBAN;
        }
    }

    /**
     * The immutable class defining the contact and regulatory data.
     */
    private static final class ContactData {
        private final String organisation;
        private final String department;
        private final String streetAddress;
        private final String cityPostcode;
        private final String departmentGenericEmail;
        private final String departmentTel;

        private ContactData() {
            this(null, null, null, null, null, null);
        }

        private ContactData(
            String organisation,
            String department,
            String streetAddress,
            String cityPostcode,
            String departmentGenericEmail,
            String departmentTel) {
            this.organisation = organisation;
            this.department = department;
            this.streetAddress = streetAddress;
            this.cityPostcode = cityPostcode;
            this.departmentGenericEmail = departmentGenericEmail;
            this.departmentTel = departmentTel;
        }

        public static ContactData of(
            String organisation,
            String department,
            String streetAddress,
            String cityPostcode,
            String departmentGenericEmail,
            String departmentTel) {
            return new ContactData(
                organisation, department, streetAddress,
                cityPostcode, departmentGenericEmail, departmentTel);
        }

        public String getOrganisation() {
            return organisation;
        }

        public String getDepartment() {
            return department;
        }

        public String getStreetAddress() {
            return streetAddress;
        }

        public String getCityPostcode() {
            return cityPostcode;
        }

        public String getDepartmentGenericEmail() {
            return departmentGenericEmail;
        }

        public String getDepartmentTel() {
            return departmentTel;
        }
    }

    /**
     * The immutable class defining the country name, SEPA status, example, and last update date.
     */
    private static final class MetaData {
        private final String    countryName;
        private final boolean   isSepa;
        private final String    ibanExample;
        private final YearMonth lastUpdate;

        private MetaData(
            String countryName,
            boolean isSepa,
            String ibanExample,
            YearMonth lastUpdate) {
            this.countryName = Objects.requireNonNull(countryName, "countryName required");
            this.isSepa = isSepa;
            this.ibanExample = ibanExample;
            this.lastUpdate = lastUpdate;
        }

        public static MetaData of(
            String countryName,
            boolean isSepa,
            String ibanExample,
            YearMonth lastUpdate) {
            return new MetaData(
                countryName, isSepa, ibanExample, lastUpdate);
        }

        public String getCountryName() {
            return countryName;
        }

        public boolean isSepa() {
            return isSepa;
        }

        public String getIbanExample() {
            return ibanExample;
        }

        public YearMonth getLastUpdate() {
            return lastUpdate;
        }
    }

}
