/*
 * Copyright © 2025-2026 Markus Spann, SpeedBankingDe
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.speedbanking.iban;

import java.lang.reflect.InvocationTargetException;

/**
 * Abstract base class for {@link CountryValidator} implementations that also carry
 * a <strong>National Check Digit (NCD)</strong> algorithm.
 * <p>
 * This class extends {@link AbstractCountryValidator} and additionally implements
 * {@link NationalCheckDigitCalculator}, making each concrete subclass simultaneously
 * a validator and a calculator for its country's NCD.
 * <p>
 * Concrete subclasses are generated by a code generator and provide the NCD algorithm
 * by extending a {@link NationalCheckDigitCalculator} inner class (e.g.
 * {@code NationalCheckDigitCalculator.AL}), so that the full inheritance chain reads:
 * <pre>
 *   NationalCheckDigitCalculator.AL    (algorithm)
 *          ↑
 *   AbstractNcdCountryValidator        (wiring + delegation)
 *          ↑
 *   CountryValidator.AL                (validateIban)
 * </pre>
 *
 * <h3>Inheritance contract</h3>
 * Subclasses must:
 * <ol>
 *   <li>implement {@link CountryValidator#validateIban(char[])};</li>
 *   <li>extend a concrete {@link NationalCheckDigitCalculator} inner class to supply
 *       {@link NationalCheckDigitCalculator#calculateNationalCheckDigit(char[])} and
 *       {@link NationalCheckDigitCalculator#validateNationalCheckDigit(char[])}.</li>
 * </ol>
 * The {@link #validateNationalCheckDigit(char[])} and
 * {@link #calculateNationalCheckDigit(char[])} methods in this class are {@code final}
 * and delegate to the captured {@code ncdCalculator} — subclasses must not override them.
 *
 * @since 1.8.5
 *
 * @see AbstractCountryValidator
 * @see CountryValidator
 * @see NationalCheckDigitCalculator
 */
abstract class AbstractNcdCountryValidator
        extends AbstractCountryValidator
        implements NationalCheckDigitCalculator {

    /**
     * The NCD algorithm for this country.
     */
    private final NationalCheckDigitCalculator ncdCalculator;

    protected AbstractNcdCountryValidator() {
        this.ncdCalculator = loadNcdCalculator(getClass());
    }

    /**
     * Loads the corresponding NCD calculator for the given validator class.
     * <p>
     * Uses reflection to instantiate the calculator defined in {@link NationalCheckDigitCalculators}.
     *
     * @param clazz the concrete validator class
     * @return the instantiated NCD calculator
     * @throws ExceptionInInitializerError if the class cannot be loaded or instantiated
     */
    static final NationalCheckDigitCalculator loadNcdCalculator(Class<? extends AbstractNcdCountryValidator> clazz) {
        String className = NationalCheckDigitCalculators.class.getName() + '$' + clazz.getSimpleName();

        try {
            Class<?> validatorClass = Class.forName(className);
            Object instance = validatorClass.getDeclaredConstructor().newInstance();
            return (NationalCheckDigitCalculator) instance;

        } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | InvocationTargetException ex) {
            throw new ExceptionInInitializerError("Could not load ncd calculator class '" + className + "': " + ex);
        }
    }

    /**
     * {@inheritDoc}
     * <p>
     * Delegates to the {@link NationalCheckDigitCalculator} captured at construction.
     */
    @Override
    public final boolean validateNationalCheckDigit(final char[] iban) {
        return ncdCalculator == null
            || !IbanConfig.isValidateNcd()
            || ncdCalculator.validateNationalCheckDigit(iban);
    }

    /**
     * {@inheritDoc}
     * <p>
     * Delegates to the {@link NationalCheckDigitCalculator} captured at construction.
     */
    @Override
    public final char[] calculateNationalCheckDigit(final char[] iban) {
        return ncdCalculator == null
            || !IbanConfig.isCalculateNcd()
            ? getCountryData().getNationalCheckDigitIndexRange().applyTo(iban)
            : ncdCalculator.calculateNationalCheckDigit(iban);
    }

    /**
     * Gets the internal NCD calculator.
     * <p>
     * Useful for subclasses or internal testing of the strategy.
     *
     * @return the calculator instance, may be {@code null}
     */
    final NationalCheckDigitCalculator getNcdCalculator() {
        return ncdCalculator;
    }

}
